### ISSUE TITLE
Can we expect a set of APIs  for fetching Call Data/Detail Record in a future release ?

### ISSUE THREAD

**Issue by arsenicraghav** [lynckia/licode#1004]
Hi,

We can see that we have some methods which can help us get stats for an incoming stream, but that is mostly geeky stats useful for developers and probably for diagnostics so wanted to know if is there any plan for CDR support coming in future release. It would really be a nice feature to have.

**Comment by lodoyun** [comment]
Please, direct questions like this to discourse.lynckia.com
