### ISSUE TITLE
can we expect the the below trailed warnings during installing the licode server

### ISSUE THREAD

**Issue by SohomHalder** [lynckia/licode#1005]
**Description**

We are observing few warnings when we install licode server. These warnings are related to compilation of erizo.js. Not sure about the impact of these warnings. Warnings are given below, kindly go through once.

  "JSC_USELESS_CODE" for few blocks and few others code block is throwing warnings like "JSC_SUSPECIOUS_SEMICOLON" and "JSC_UNREACHABLE _CODE", but this warnings are not creating any blockage in running the over all application indeed .
Now my query is shall I expect the same warnings all the time during running the application, or  it is going to frame a bigger issue in future.

**Steps to reproduce the issue:**
1.  install Licode server

**Describe the results you received:**

dist/debug/erizo/erizo.js:2628 (JSC_USELESS_CODE) -----present in many placeses
Suspicious code. The result of the 'not' operator is not being used.

dist/debug/erizo/erizo.js:2628 (JSC_SUSPICIOUS_SEMICOLON)
If this if/for/while really shouldn''t have a body, use '{}'

dist/debug/erizo/erizo.js:3257 (JSC_UNREACHABLE_CODE)
unreachable code

**Comment by lodoyun** [comment]
Those are google-closure-compiler warnings. You can safely ignore them and they won't show up  in the browser when running the application.
