### ISSUE TITLE
erizoAge  print a lot of unknownSSRC  log 

### ISSUE THREAD

**Issue by wuxingzhong** [lynckia/licode#1007]
_licode_1  | 09:58:28 2|erizoAge | [erizo-a334dd2d-a4a8-5055-ce66-b3916a0c638f] 2017-08-11 09:58:28,249  - DEBUG [0x7f1f25ffb700] WebRtcConnection - id: 380192714187893500,  unknownSSRC: 2147484093, localVideoSSRC: 3836616303, localAudioSSRC: 1542262221
l_licode_1  | 09:58:28 2|erizoAge | [erizo-a334dd2d-a4a8-5055-ce66-b3916a0c638f] 2017-08-11 09:58:28,249  - DEBUG [0x7f1f277fe700] WebRtcConnection - id: 380192714187893500,  unknownSSRC: 2147484103, localVideoSSRC: 3836616303, localAudioSSRC: 1542262221
l_licode_1  | 09:58:28 2|erizoAge | [erizo-a334dd2d-a4a8-5055-ce66-b3916a0c638f] 2017-08-11 09:58:28,249  - DEBUG [0x7f1f24ff9700] WebRtcConnection - id: 380192714187893500,  unknownSSRC: 2147484026, localVideoSSRC: 3836616303, localAudioSSRC: 1542262221
l_licode_1  | 09:58:28 2|erizoAge | [erizo-a334dd2d-a4a8-5055-ce66-b3916a0c638f] 2017-08-11 09:58:28,249  - DEBUG [0x7f1f26ffd700] WebRtcConnection - id: 380192714187893500,  unknownSSRC: 2147483791, localVideoSSRC: 3836616303, localAudioSSRC: 1542262221
l_licode_1  | 09:58:29 2|erizoAge | [erizo-689c7537-6a9f-646a-0b4a-05a43b54c5d0] 2017-08-11 09:58:29,150  - DEBUG [0x7efdf37fe700] WebRtcConnection - id: 156140426092413440,  unknownSSRC: 2147483734, localVideoSSRC: 771271542, localAudioSSRC: 0
l_licode_1  | 09:58:29 2|erizoAge | [erizo-a334dd2d-a4a8-5055-ce66-b3916a0c638f] 2017-08-11 09:58:29,161  - DEBUG [0x7f1f277fe700] WebRtcConnection - id: 380192714187893500,  unknownSSRC: 2147484104, localVideoSSRC: 3836616303, localAudioSSRC: 1542262221
l_licode_1  | 09:58:29 2|erizoAge | [erizo-689c7537-6a9f-646a-0b4a-05a43b54c5d0] 2017-08-11 09:58:29,351  - DEBUG [0x7efdfcb46700] WebRtcConnection - id: 156140426092413440,  unknownSSRC: 2147483808, localVideoSSRC: 771271542, localAudioSSRC: 0
l_licode_1  | 09:58:29 2|erizoAge | [erizo-a334dd2d-a4a8-5055-ce66-b3916a0c638f] 2017-08-11 09:58:29,161  - DEBUG [0x7f1f25ffb700] WebRtcConnection - id: 380192714187893500,  unknownSSRC: 2147484094, localVideoSSRC: 3836616303, localAudioSSRC: 1542262221
l_licode_1  | 09:58:29 2|erizoAge | [erizo-05121591-a268-5d05-df03-3322b2ca7e9d] 2017-08-11 09:58:29,486  - DEBUG [0x7f148a194700] WebRtcConnection - id: 358390284306108400,  unknownSSRC: 2412642309, localVideoSSRC: 1309889003, localAudioSSRC: 234462204
l_licode_1  | 09:58:29 2|erizoAge | [erizo-a334dd2d-a4a8-5055-ce66-b3916a0c638f] 2017-08-11 09:58:29,161  - DEBUG [0x7f1f277fe700] WebRtcConnection - id: 380192714187893500,  unknownSSRC: 2147484105, localVideoSSRC: 3836616303, localAudioSSRC: 1542262221
l_licode_1  | 09:58:29 2|erizoAge | [erizo-a334dd2d-a4a8-5055-ce66-b3916a0c638f] 2017-08-11 09:58:29,161  - DEBUG [0x7f1f277fe700] WebRtcConnection - id: 380192714187893500,  unknownSSRC: 2147483729, localVideoSSRC: 3836616303, localAudioSSRC: 1542262221
l_licode_1  | 09:58:29 2|erizoAge | [erizo-a334dd2d-a4a8-5055-ce66-b3916a0c638f] 2017-08-11 09:58:29,161  - DEBUG [0x7f1f24ff9700] WebRtcConnection - id: 380192714187893500,  unknownSSRC: 2147484027, localVideoSSRC: 3836616303, localAudioSSRC: 1542262221

**Comment by lodoyun** [comment]
Please use the issue template, we need all the details we request in it.

**Comment by wuxingzhong** [comment]
ok! 
thanks!

**Comment by wangbing8895** [comment]
@wuxingzhong Hi,have you solved the problem  about unknownSSRC?
