### ISSUE TITLE
BaseStack.js and/or adapter.js - which one of these is being used currently in Licode  ?

### ISSUE THREAD

**Issue by arsenicraghav** [lynckia/licode#1009]
Can someone confirm which of these(BaseStack.js or adapter.js) are we using currently in Licode ? I am a little confused about the usage of these files, a little description on both and where they are used would be nice.

**Comment by lodoyun** [comment]
I'll answer it here this time but please don't ignore the issue template. If your question does not fit within the issue template (like this one), most likely it's not an issue and should be posted in [discourse.lynckia.com](discourse.lynckia.com).

We're using both. `adapter.js` provides a shimmy for the WebRTC API itself. `BaseStack` encapsulates how licode uses the API.
