### ISSUE TITLE
How to Playing recorded streams?

### ISSUE THREAD

**Issue by pumpkin918** [lynckia/licode#1010]
I see document in "Client API"
var stream = Erizo.Stream({video: true, audio: false, url:"file:///path_to_file/previousRecording.mkv"});
room.publish(stream);
var stream2 = Erizo.Stream({audio:true, video:true, recording: 'asda2131231'});
room.publish(stream2);

I add a button in Exmaple（/licode/extras/basic_example/public/script.js）
localStream.close();
localStream = Erizo.Stream({video: true, audio: true, url: "file:///data/video/5.mkv"});
room.publish(localStream);

first I record  a mkv file 6 minutes,after i attempt to play the record video,but it all ways in load status,load can play the last 3 minutes.

![image](https://user-images.githubusercontent.com/29752565/29403319-991b3e5e-836a-11e7-92e7-8d51ab977543.png)

**Comment by pumpkin918** [comment]
as see from right, The playback video is always loaded?

**Comment by jcague** [comment]
you'll probably need to post-process the video with ffmpeg, otherwise it will be hard to play it due to different reasons, like not having periodic keyframes.

**Comment by jcague** [comment]
please, use the issue template the next time, thanks!
