### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by youminxue** [lynckia/licode#1017]
**Description**
build ./scripts/installErizo.sh
error INFO：
[ 58%] Linking CXX shared library liberizo.dylib
Undefined symbols for architecture x86_64:
  "_EVP_aes_128_ctr", referenced from:
      _srtp_aes_icm_openssl_context_init in libsrtp2.a(aes_icm_ossl.o)
  "_EVP_aes_128_gcm", referenced from:
      _srtp_aes_gcm_openssl_context_init in libsrtp2.a(aes_gcm_ossl.o)
  "_EVP_aes_192_ctr", referenced from:
      _srtp_aes_icm_openssl_context_init in libsrtp2.a(aes_icm_ossl.o)
  "_EVP_aes_256_ctr", referenced from:
      _srtp_aes_icm_openssl_context_init in libsrtp2.a(aes_icm_ossl.o)
  "_EVP_aes_256_gcm", referenced from:
      _srtp_aes_gcm_openssl_context_init in libsrtp2.a(aes_gcm_ossl.o)
  "_SSL_CTX_set_tlsext_use_srtp", referenced from:
      dtls::DtlsSocketContext::DtlsSocketContext() in DtlsClient.cpp.o
      dtls::DtlsSocketContext::setSrtpProfiles(char const*) in DtlsClient.cpp.o
  "_SSL_export_keying_material", referenced from:
      dtls::DtlsSocket::getSrtpSessionKeys() in DtlsSocket.cpp.o
  "_SSL_get_selected_srtp_profile", referenced from:
      dtls::DtlsSocket::getSrtpProfile() in DtlsSocket.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Licode commit/release where the issue is happening**

**Additional environment details (Local, AWS, Docker, etc.):**

**Comment by jcague** [comment]
please fill in more info if you still have this problem. Also, try to use Ubuntu 14.04, we build Licode every day using a fresh Ubuntu server (using docker and it seems to work).
