### ISSUE TITLE
Rename recordings that are stored on the server

### ISSUE THREAD

**Issue by evilword666** [lynckia/licode#1024]
I'm trying to save the recordings with the user name that is added to the room, I see that to rename the recordings I have to edit the variable recordingId in the erizoController.js  file , but this leaves me a static name for all recordings and I want the recordings to be saved with the name of the user that is added to the room. Does anyone know how to do this?

**Comment by evilword666** [comment]
I solved this by equating the variable user.name of the listen function inside the variable var recordingId

I hope it helps

**Comment by jcague** [comment]
thanks!
