### ISSUE TITLE
Muting local Audio/Video Stream

### ISSUE THREAD

**Issue by peili** [lynckia/licode#103]
To mute Audio or Video right now we always have to init Erizo.Stream again.
I would recommend to add a function while the local stream is established.
Like localStream.muteVideo()

Right now I help my self with: localStream.stream.getVideoTracks()[0].enabled = true/false However if disabled the viewer only gets a black screen.

So also SDP should be modified e.g.:
case 'mute':
                                    sdp.media[1] = sdp.media[1].replace('a=sendrecv', 'a=recvonly');
                                    break
case 'unmute':
                                    sdp.media[1] = sdp.media[1].replace('a=recvonly', 'a=sendrecv')

**Comment by DevJhns** [comment]
@ghost @jcague
wow, I meet same behaviour now,
if some of my  users set localStream.getVideoTracks()[0].enabled=false
before call or while connecting, then sometimes one or more users dont hear other, but if they turn camera on then audio appears,
met this behaviour only on mac/ipad/iphone
