### ISSUE TITLE
MP3 sounds discontinuous

### ISSUE THREAD

**Issue by nineKnight** [lynckia/licode#1050]
When we test the basic example under extras, we notice the problem as the title describes.
We just play a MP3 song close to the webcam(with a mic), and hear discontinuous music from a headset(without a mic).

Is there any way to solve it?

**Comment by kekkokk** [comment]
Sure, you have to disable echoCancellation in constraints when you make the getusermedia.
ex: {"audio":{"optional":[],"mandatory":{"echoCancellation":"false"}}

**Comment by nineKnight** [comment]
Thank you. @kekkokk 
If I disable echoCancellation in constraints, meanwhile, I need echo cancellation, I have to turn to third-party software, right?

**Comment by kekkokk** [comment]
Sorry I can't understand your question. You think at your audio stream as a tunnel. in this tunnel flows every audio packet you send. if you want that audio to arrive at the other end "as is" you need to turn echo cancellation off (is on by default). so if you pass an mp3 all frequencies arrive at the other end untouched. If you turn echocancellation on, chrome will cut off lots of frequencies. this is very useful for voice stream but an mp3 will not sound like the original.
You have to choose what you want more

**Comment by nineKnight** [comment]
@kekkokk thank you again. Actually, I thought if echoCancellation in constraints made audio discontinuous, I could find a software to do echocancellation which wouldn't make audio that discontinuous. I know your meaning and after your comment it seems that I know what echocancellation does to the audio and I thought in a wrong way.
