### ISSUE TITLE
Ice failed question?

### ISSUE THREAD

**Issue by yangjinecho** [lynckia/licode#1054]
I deploy licode  and coturn on same machine, the machine has a public ip. I open the udp/tcp 3478 port
I only set stun address, no turn.
In  different network environment, some can access licode, some can not.
when I also set turn server ,all can access it (direct or relay )
Anyone can explain this for me, as i think the server has a public ip, i can access it in any environment, do not need turn server. 
Please help me, sorry for my pool english.

**Comment by jcague** [comment]
please ask questions in [discourse](http://discourse.lynckia.com/)
