### ISSUE TITLE
SdpInfo.js wrong behavior in simulcast

### ISSUE THREAD

**Issue by kekkokk** [lynckia/licode#1076]
Hi, 
I'm facing some issue with firefox Simulcast.
I think that there's something handled in the wrong way in the new SDPInfo.js
https://github.com/lynckia/licode/pull/1075

Before this push, everything worked fine. We made few adjustments in c++ to make firefox simulcast works.
(Client side) I'm calling the .enableSimulcast() function in the SdpHelpers BEFORE creating the offer. Firefox then generates an offer with:

> a=simulcast: send rid=spam;egg
> a=ssrc:1099767458 cname:{299dbffc-d388-8644-b3d2-8974094ff9df}
> a=ssrc:1589187499 cname:{299dbffc-d388-8644-b3d2-8974094ff9df}

then setLocalDescForOffer is called and then the sdps flows into SemanticSdp.SDPInfo.processString:

    that.localSdp = SemanticSdp.SDPInfo.processString(that.localDesc.sdp);

The problem is that the 
> a=simulcast: send rid=spam;egg

directive disappear. 

[THIS](https://www.diffchecker.com/v3C92ZpJ) is the difference between the generated sdps from the browser (untouched) and the processed sdps from SdpInfo.
As you can see the a=simulcast get lost and there's also duplicate

> a=ssrc:1589187499 cname:{299dbffc-d388-8644-b3d2-8974094ff9df}
> a=ssrc:1589187499 cname:{299dbffc-d388-8644-b3d2-8974094ff9df}

**Comment by jcague** [comment]
sorry, we don't support Firefox simulcast currently in the repository, so I can't help. But you have two options: you can find the bug and submit a patch to the SdpInfo or, even better ;), submit the code that makes Firefox simulcast work!

**Comment by kekkokk** [comment]
I can push the code tomorrow with no problem, I submit everything I do (see the update to latest libnice).
But It will not work cause of the issue. If you can point me in the direction to comprehend why the a=simulcast line gets dropped, I can solve then PR.

**Comment by jcague** [comment]
sure! probably I can fix it in the same Firefox Simulcast PR with the rest of the code if you prefer.

**Comment by kekkokk** [comment]
Still, I see the duplicate 

> a=ssrc:1589187499 cname:{299dbffc-d388-8644-b3d2-8974094ff9df}
> a=ssrc:1589187499 cname:{299dbffc-d388-8644-b3d2-8974094ff9df}

cname as a bug
