### ISSUE TITLE
Simulcast no longer works

### ISSUE THREAD

**Issue by kekkokk** [lynckia/licode#1079]
After PR https://github.com/lynckia/licode/pull/1075 simulcast in chrome no longer works.

**Steps to reproduce the issue:**
1. join with Chrome tab in http://localhost:3001/?simulcast=true
2. join with another Chrome tab in http://localhost:3001/?onlySubscribe=true
3. open http://localhost:3001/quality_layers.html 

**Describe the results you received:**
The quality remain in the low layer

![screen shot 2017-12-01 at 7 00 06 pm](https://user-images.githubusercontent.com/15072723/33496273-e1a0240c-d6c9-11e7-8c35-d17483329f7f.png)

**Describe the results you expected:**
Works as expected

**Additional information you deem important (e.g. issue happens only occasionally):**
Tried to also force the quality layer with remotestram._setStaticQualityLayer(1,2)

the command is ignored, still receiving low spatial layer.

**Licode commit/release where the issue is happening**
e6cd88b32e008ec1342cfd6024b83a506a2caebe

**Additional environment details (Local, AWS, Docker, etc.):**
tried in localhost (OSX).
the commit before, works as expected

**Comment by lodoyun** [comment]
Thanks for the details and for your time testing different commits.
We're aware of the issue, it does look like there is a problem with the new generated SDP and it does not play nicely with our simulcast implementation.
We should have a solution soon.

**Comment by ChukwudiUzoma** [comment]
@lodoyun Please how do I modify the spatial and temporal layer in Chrome developer console?
room.remoteStreams.get(id)._setStaticQualityLayer(spatialLayer, temporalLayer)  doesnt work. Thanks

**Comment by lodoyun** [comment]
@ChukwudiUzoma It should work. Check that simulcast is working and you're not using either v4 or the latest code

**Comment by ChukwudiUzoma** [comment]
@lodoyun Thanks mate, fixed it. It was just a browser problem.
