### ISSUE TITLE
Dangling pointer in logging pattern

### ISSUE THREAD

**Issue by Trisfald** [lynckia/licode#1091]
There's a potential issue with a pattern commonly used to print logs. For example in MediaStream.h:

```
inline const char* toLog() {
  return ("id: " + stream_id_ + ", " + printLogContext()).c_str();
}
```

This creates a temporary std::string and returns the pointer to its internal buffer. The pointer is later used by the logging macro, but it outlives the lifetime of the string leading to undefined behavior.

I suggest changing the function to:

```
inline std::string toLog() {
  return ("id: " + stream_id_ + ", " + printLogContext());
}
```

and usage to:

```
const auto log_str = toLog();
ELOG_XXX("%s", log_str.c_str());
```

in MediaStream.h, IceConnection.h, Transport.h, WebrtcConnection.h

If you also think this's a problem, I can do a PR to fix!

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Licode commit/release where the issue is happening**
Master

**Additional environment details (Local, AWS, Docker, etc.):**

**Comment by lodoyun** [comment]
Agreed, that looks like a more sound solution 👍 
Please go ahead and do the PR if you have the time for it.

Thanks!
