### ISSUE TITLE
Cannot read property 'sendMessage' of undefined

### ISSUE THREAD

**Issue by felix28** [lynckia/licode#1117]
Good day,

I have an issue in setting up Licode as HTTPS.

I follow the blog at http://lynckia.com/licode/nginx-dep.html.

The only difference I did is setting the hostname to

config.erizoController.hostname = 'myhostname.com'; //default value: '

Then when I run the Basic Example, I can connect to the Room but after that it says 
STREAM FAILED, DISCONNECTION. This is how my Basic Example look like:

- Mic and Cam OK
- Connected to the room OK
- STREAM FAILED, DISCONNECTION

When I look at the console it says "Cannot read property 'sendMessage' of undefined"  in erizo.js file.

Please help

Thanks

**Comment by kekkokk** [comment]
did your hostname have a public ip?
is your host behind a nat or your client behind a firewall or an asymmetric nat?
maybe you need to setup a turn server in order to reach your licode environment

**Comment by felix28** [comment]
yes. I have a public IP.

Now, I discovered that in Basic Example, if I disable audio and video, only data is enable, everything works perfectly. Basically, you can have a text chat. But we don't need text chat. We are developing an audio application.

**Comment by felix28** [comment]
This issue is now solved. @kekkokk  Thanks for your help. For those who experience the same problem I faced, you need to set config.cloudProvider.name = 'amazon'; in licode_config.js file. This configuration is applicable if you are hosted in AWS
