### ISSUE TITLE
Error in Channel.js

### ISSUE THREAD

**Issue by chaome** [lynckia/licode#1168]
Hi,

There is an error in latest code( commit d694a996c481a762dcd57494f71c294307965828), as you can see it in the screen shot images, the value of parameter "options" is in fact the token value, is this a typo?

![image](https://user-images.githubusercontent.com/13973965/37501088-ab4f13be-2907-11e8-96dd-7272f8585f52.png)

![image](https://user-images.githubusercontent.com/13973965/37501150-f72fd160-2907-11e8-8741-6633f98d0501.png)

**Comment by jcague** [comment]
that's intended, you should update your clients too since changes are not backwards compatible yet.
