### ISSUE TITLE
GET polyblob:1 net::ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by peiying16** [lynckia/licode#1175]
**Description**

![image](https://user-images.githubusercontent.com/25106861/37783835-ce4a2d30-2dcc-11e8-9d69-b3425a61d9d8.png)

Try to `play()` stream on my vuejs app. It shows this error. The video is black. I'm sure it is successfully published.

Copy the code to another app (not vuejs). It works perfectly. 

Any idea for this error?

**Comment by peiying16** [comment]
Just found the reason. When the app has another socket connection, it will give this error. If I remove the socket connection, it works perfectly.

**Comment by cbrem** [comment]
More generally, it seems like this issue can only appear when using the deprecated `window.URL.createObjectURL()` method. Using the replacement (https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/srcObject) seems to fix things.

**Comment by peiying16** [comment]
This helps. Thanks @cbrem
