### ISSUE TITLE
ErizoList.js cannot get list of Erizos (

### ISSUE THREAD

**Issue by khoachung89** [lynckia/licode#1197]
I'm installing Licode on my Ubuntu machine at local following the guide on: [http://lynckia.com/licode/install.html](http://lynckia.com/licode/install.html)
I also install and run the basic example.
As the requirement, the whole system need to be served over ssl, i have installed nginx and configure it as a proxy and redirect all request to basic example (on port 3000). My nginx configuration as below:

`upstream licode {
    server 127.0.0.1:3001;
}

server {
	listen 443;
	server_name 192.168.126.133;
	ssl on;
	ssl_certificate /home/chung/ssl/selfsigned.crt;
	ssl_certificate_key /home/chung/ssl/selfsigned.key;
	ssl_session_timeout 5m;
    	ssl_protocols  SSLv2 SSLv3 TLSv1;
    	ssl_ciphers  HIGH:!aNULL:!MD5;
    	ssl_prefer_server_ciphers   on;
        #ssl_dhparam /etc/ssl/certs/dhparam.pem;
        ssl_stapling on;
        ssl_stapling_verify on;
        add_header Strict-Transport-Security max-age=15768000;

	location ~ ^/(.+\.(?:js|css|png|jp?g|gif|swf|ico|pdf|pdfx|mov|fla|zip|rar))$ {
        	alias /home/chung/licode/extras/basic_example/public;
        	try_files /$1 =404;

        	access_log off;
        	expires max;
	        add_header Pragma public;
        	add_header Cache-Control "public, must-revalidate, proxy-revalidate";
    	}

	location ~ ^/(.*)$ {
        	access_log off;
        	proxy_pass http://licode;
        	proxy_set_header X-Real-IP $remote_addr;
	        proxy_set_header Host $host;
        	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

	        # WebSocket support (nginx 1.4)
        	proxy_http_version 1.1;
	        proxy_set_header Upgrade $http_upgrade;
	        proxy_set_header Connection "upgrade";

        	# Path rewriting
	        rewrite /licode$ / break;
        	rewrite /licode/(.*) /$1 break;
	        proxy_redirect off;
    	}
}`

Now, i can go to my browser and start testing.
I can see that i have joined the room already (as the test shown in the attached image)
![licodebug](https://user-images.githubusercontent.com/4082657/38791605-f22999fc-4172-11e8-93f8-c02cf7019fff.PNG)
However i checked the Google Chrome console and see an error:
`WebSocket connection to 'ws://192.168.126.133:8080/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`
Look back to the server, i caught from node:
`2018-04-16 12:24:33.400  - INFO: RoomController - message: addPublisher, clientId f02ff379-ac26-4d63-8e72-c2412526c26f, streamId: 815828529653308300, state: erizo, data: true, audio: true, video: true, label: 8r1UmXYf98w8SVxctoEVLrPsKeMVEB2WjB2S, muteStream: [Object], minVideoBW: 0, maxVideoBW: 300, mediaConfiguration: default, singlePC: false,
/home/chung/licode/erizo_controller/erizoController/models/ErizoList.js:39
    return this.erizos[this.getInternalPosition(position)].pending;
                                                          ^

TypeError: Cannot read property 'pending' of undefined
    at ErizoList.isPending (/home/chung/licode/erizo_controller/erizoController/models/ErizoList.js:39:59)
    at waitForErizoInfoIfPending (/home/chung/licode/erizo_controller/erizoController/roomController.js:84:18)
    at getErizoJS (/home/chung/licode/erizo_controller/erizoController/roomController.js:100:11)
    at Object.that.addPublisher (/home/chung/licode/erizo_controller/erizoController/roomController.js:223:13)
    at Client.onPublish (/home/chung/licode/erizo_controller/erizoController/models/Client.js:186:30)
    at emitThree (events.js:116:13)
    at Socket.emit (events.js:194:7)
    at /home/chung/licode/node_modules/socket.io/lib/socket.js:514:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

Of course, after throwing this exception, Licode cannot work anymore. I'm not sure what's wrong here.

**Comment by nvazquezg** [comment]
This happened to us too, is a problem with the recent commits. A workaround is to set a value greater than 0 in licode_config.js to:
config.erizoController.maxErizosUsedByRoom
