### ISSUE TITLE
recording with h264 no file 

### ISSUE THREAD

**Issue by peererror** [lynckia/licode#1260]
I am trying to record audio/video stream on server using licode api 
When I use vp8 +opus the mkv file is created and it is playable . But when I use h264 and disable vp8 I don't see the .mkv file and there are no errors on the console . following is the output

INFO: ErizoController - Client - message: startRecorder, state: RECORD_STARTED, streamId: 660921798280602200 ....

2018-07-13 02:54:35.742  - INFO: ErizoController - Client - message: startRecorder, state: RECORD_STOPPED, streamId: 20105865787430012, url: /home/ ..........

INFO: ErizoController - Client - message: startRecorder, state: RECORD_STOPPED, streamId: 163452811898851420 ............

is there a way to record h264 video .? or licode only support vp8 video file recording 

Regards

**Comment by nvazquezg** [comment]
Check the comments in this PR: https://github.com/lynckia/licode/pull/1124

**Comment by peererror** [comment]
Thanks for pointing that out now I can record file using h264 but there is no audio in the .mkv file
