### ISSUE TITLE
 lib not found: SRTP-NOTFOUND when installing Erizo

### ISSUE THREAD

**Issue by harlanc** [lynckia/licode#1279]
When install the Erizo using the following command:

haha@hahadeMacBook-Pro ~/g/licode> ./scripts/installErizo.sh

Error happens:

Installing erizo...
generating release
-- Found glib-2.0: /usr/local/include/glib-2.0, /usr/local/lib/libglib-2.0.dylib;/usr/local/lib/libgobject-2.0.dylib;/usr/local/lib/libgthread-2.0.dylib
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   thread
--   regex
--   system
--   chrono
--   date_time
--   atomic
CMake Error at CMakeLists.txt:7 (message):
  lib not found: SRTP-NOTFOUND check README
Call Stack (most recent call first):
  CMakeLists.txt:77 (test_lib)

-- Configuring incomplete, errors occurred!
See also "/Users/zexu/github/licode/erizo/build/release/CMakeFiles/CMakeOutput.log".

I don't know why. My platform is OSX 10.13.6 and licode branch is master.

**Comment by kekkokk** [comment]
Did you run installMacDeps.sh before installErizo?

**Comment by harlanc** [comment]
yes, I have run the script

**Comment by harlanc** [comment]
fixed.only reinstall relevant scripts..

**Comment by JiangangYang** [comment]
@kekkokk 请问你如何解决的？我也遇到这个问题了
