### ISSUE TITLE
How to choose resolutions under simulcast?

### ISSUE THREAD

**Issue by lidedongsn** [lynckia/licode#1282]
How the Chrome choose video resolutions when using simulcast? And How licode decide which ssrc stream send to subsciriber ？

**Comment by kekkokk** [comment]
chrome choose video resolutions based on available bandwidth and based on how many spatial layes you define here:
https://github.com/lynckia/licode/blob/ef89a6dda98bab079e9f757cdd4e89a584ff80ae/erizo_controller/erizoClient/src/webrtc-stacks/ChromeStableStack.js#L9

I think that with newer chrome that supports transceivers you will be able to specify them but I'm not sure.

Erizo does a probe to clients when sending video packets injecting some padding. this will result in a higher bandwidth sent and if the REMBS of this clients increases, erizo will start sending an higher resolution and vice versa.

https://github.com/lynckia/licode/blob/master/erizo/src/erizo/rtp/LayerBitrateCalculationHandler.cpp here
https://github.com/lynckia/licode/blob/master/erizo/src/erizo/rtp/QualityFilterHandler.cpp here
and https://github.com/lynckia/licode/blob/master/erizo/src/erizo/rtp/SenderBandwidthEstimantionHandler.cpp here

**Comment by lidedongsn** [comment]
frame rate is also changed while subscribing

**Comment by kekkokk** [comment]
yeah, that's are called temporal layers.
Chrome automatically choose, based on available bandwidth and spatial layers, how many send. usually 3 for each layer, ~ 7, 15, and 30 fps

**Comment by lidedongsn** [comment]
Can I make it constant? I want to subscribe **const** framerate and resolution in some cases.

**Comment by kekkokk** [comment]
sure! https://github.com/lynckia/licode/blob/5b49a126c3332eb5c8aed2e70fc1ba3e0bdfa6d6/erizo_controller/erizoClient/src/Stream.js#L399

**Comment by lidedongsn** [comment]
Great! I just test it. It really wroks! now, the publisher's simulcast streams is not in control(only set a base resolution, [simulcast.cc:61](https://cs.chromium.org/chromium/src/third_party/webrtc/media/engine/simulcast.cc?sq=package:chromium&g=0&l=61)const SimulcastFormat kSimulcastFormats[] = {
  {1920, 1080, 3, 5000, 4000, 800},
  {1280, 720, 3,  2500, 2500, 600},
  {960, 540, 3, 900, 900, 450},
  {640, 360, 2, 700, 500, 150},
  {480, 270, 2, 450, 350, 150},
  {320, 180, 1, 200, 150, 30},
  {0, 0, 1, 200, 150, 30}
};), subscribers need to know What are the streams publisher has， I'll see the licode. thk you so mush! ^V^

**Comment by kekkokk** [comment]
it doesn't make sense. since if there's only one publisher and one subscriber both browser signal RRs and REMBS to achieve the best resolution and bitrate possible. in a many to many scenario you want to have simulcast active but subscribers would't even know that is a simulcast stream since licode do the translation of sequence numbers between different resolution layers in a way that the stream comes transparently in one stream to the subscribers

**Comment by lidedongsn** [comment]
THKS.
