### ISSUE TITLE
Setting DSCP value

### ISSUE THREAD

**Issue by ashar02** [lynckia/licode#1346]
Is there any way I can set DSCP value for audio and video streams for QOS purposes?

**Comment by ashar02** [comment]
@jcague can you please guide me regarding this query?

**Comment by jcague** [comment]
I found this among the references i have: http://www.rtcbits.com/2017/01/using-dscp-for-webrtc-packet-marking.html

**Comment by ashar02** [comment]
Thanks I shall try this.
