### ISSUE TITLE
API for playback/record

### ISSUE THREAD

**Issue by yossiliron** [lynckia/licode#135]
Currently, there's not a lot (if any) documentation of the record/playback functionality.
(which is expected for a feature undergoing development...)
Several issues/suggestions concerning this future API from code reading and trial/error:
1. The URL for recording should be accessible to the application, in order to store it in database for later playback. Either pass the URL to the startRecording(), or introduce a getter for the URL being used
2. The recording in Erizo is applied per stream instance, but it is the room object that has a  member "recordingUrl". Furthermore, the startRecording function uses another (non member) variable also named  "recordingUrl". Suggestion: Keep "recordingUrl" local to the function, but return its value so that the application can memorize it.
3. Playback is not documented. Code reading suggests the following procedure:
    a. Browser script: Open a new Erizo stream with URL assigned to memorized URL
    b. Browser : Publish the stream to the room and wait for the add-stream event
    c. Erizo : Creates a new stream from Internal source and signal its addition to room members
    d. Browser: Attached the added stream to a video tag as if it was any other peer connection.
The above procedure "almost" works, but ends up with a black window at the browser. The recording files was verified with VLC

Any comments/suggestion are appreciated

**Comment by zevarito** [comment]
@lodoyun Documentation says...

"This file can be played directly or streamed into a Licode room."

I downloaded mkv file and it is not playable with the browser like file:///some.mkv

Could you confirm the resultant recording has no need of transcoding?

Thanks!
