### ISSUE TITLE
Horizontal Scalbility, simulcast and use of Turn servers

### ISSUE THREAD

**Issue by madabhaviamit** [lynckia/licode#1351]
Hi there,

Need to understand the following:

1. whether licode supports horizontal scalability, i.e, if i use multiple servers, will licode work as it will for a single server on multiple servers?
2. Does licode uses any STUN and TURN Servers internally and does it use webscokets?
3. Does licode supports simulcast?
4. Can i use only Erizo.stream without the use of the Erizo.room to extend my application to be capable of doing multiparty calls?
5. does licode supports only SFU or SFU and MCU both, what shall i have to do if i only want SFU to be supported with licode?

**Comment by kekkokk** [comment]
1) yes licode can scale on multiple servers.
2) no you have to provide your own if you use it behind NAT, not necessary (serverside) if your servers are open. and yes, as I said before use websockets to pass the signaling informations.
3) yes, currently vp8 simulcast and vp9 svc are implemented. 
4) you need to study the architecture and see if is suitable for your use. anything can be done
5) only sfu is supported. it is also capable of stream recording but they are not very well synched and need a transcode afterwards

**Comment by madabhaviamit** [comment]
Hi kekkokk,

Thanks for your response, the information provided was very esssential to me.

Also, i am trying to run licode on my local machine and i pulled it from docker hub using "**sudo docker pull lynckia/licode**" and i ran it on my localhost as **"http://localhost:3001/"** and it works fine. 

But, when i tried to access the local machine from other machine in the same lan network with ip(like this http://10.29.130.79:3001/) gives me a getusermedia() error. since getusermedia() does not work with insecure origin.

Can you please help me with how do i run the same using docker with "**https://localhost:3001/**"?
is there any configuration needs to be done and in which file if yes? 

> 1. yes licode can scale on multiple servers.
> 2. no you have to provide your own if you use it behind NAT, not necessary (serverside) if your servers are open. and yes, as I said before use websockets to pass the signaling informations.
> 3. yes, currently vp8 simulcast and vp9 svc are implemented.
> 4. you need to study the architecture and see if is suitable for your use. anything can be done
> 5. only sfu is supported. it is also capable of stream recording but they are not very well synched and need a transcode afterwards

Hi kekkokk,

Thanks for your response, the information provided was very esssential to me.

Also, i am trying to run licode on my local machine and i pulled it from docker hub using "**sudo docker pull lynckia/licode**" and i ran it on my localhost as **"http://localhost:3001/"** and it works fine. 

But, when i tried to access the local machine from other machine in the same lan network with ip(like this http://10.29.130.79:3001/) gives me a getusermedia() error. since getusermedia() does not work with insecure origin.

Can you please help me with how do i run the same using docker with "**https://localhost:3001/**"?
is there any configuration needs to be done and in which file if yes?

**Comment by kekkokk** [comment]
yes, you need to modify the licode_config.js file in your project root directory (idk how to modify it in the docker container) and set 

```
config.erizoController.ssl = true; // default value: false
config.erizoController.listen_ssl = true; // default value: false
```

The new port to connect is 3004
in this way the other pc would complain about the certificate that is self signed but if you open https://10.29.130.79:8080/ and accept certificate, the next reload should works.

Chrome has a strict policy about webrtc used on non https website, only localhost is whitelisted.

The other option would be setting nginx to terminate ssl and leave licode ssl = false.
[Licode website](http://lynckia.com/licode/nginx-dep.html)

other options would be add a self signed certificate and modify hosts file on both pc to point at the domain specified in the certificate (also need to modify the licode_config.js hostname)

But the first described option is way more faster to be able to explore licode at first

**Comment by madabhaviamit** [comment]
> yes, you need to modify the licode_config.js file in your project root directory (idk how to modify it in the docker container) and set
> 
> ```
> config.erizoController.ssl = true; // default value: false
> config.erizoController.listen_ssl = true; // default value: false
> ```
> The new port to connect is 3004
> in this way the other pc would complain about the certificate that is self signed but if you open https://10.29.130.79:8080/ and accept certificate, the next reload should works.
> 
> Chrome has a strict policy about webrtc used on non https website, only localhost is whitelisted.
> 
> The other option would be setting nginx to terminate ssl and leave licode ssl = false.
> [Licode website](http://lynckia.com/licode/nginx-dep.html)
> 
> other options would be add a self signed certificate and modify hosts file on both pc to point at the domain specified in the certificate (also need to modify the licode_config.js hostname)
> 
> But the first described option is way more faster to be able to explore licode at first

Hi kekkokk,

Thanks for your response. 

I had just changed the port from 3001 to 3004 while running the docker container and was able to proceed with the secure http with providing exception for the domain in the browser. However, now i ran into a new problem where i was trying to connect over **ws** instead of **wss** on my localhost.

I think i should proceed with building from source instead of using the docker container because there i would be able to edit the contents of the file and proceed further. 
I work in an organization and we already developed 1:1 video calling capability using the raw webrtc and we also have our own signalling server on top of hazelcast cluster for users availability(whether the user is online or offline) . Now we had planned to develop multiparty video call capability in our webapp.

However, we do not use socket io, instead we use java websockets and java message passing service(JMS of java EE 7).

I am planning to use the same JMS for the next development plans for signalling and i just want to use the raw SFU capability to route the media.

Also we cannot use rabbitmq and mongodb in our architecture

Following are some more queries from myside :

1. I am not willing to use socket io, can i do that still taking the use of Licode?
2. will it be easy for me to use the licode with java EE 7 and hazelcast for user management?

**Comment by jcague** [comment]
Those requirements seems to hard just to take part of the raw SFU capability. Of course, you can try to do that, but it entails multiple risks. Even if you manage to do it shortly you have to think about maintainability with futures updates of Licode.
