### ISSUE TITLE
config turn-server with ALTERNATE-SERVER Mechanism failed

### ISSUE THREAD

**Issue by dqgv587** [lynckia/licode#1352]
Hi there,
When construct a video conference project, I get a problem about TURNSERVER. details as following:
1. config one turnserver, everything is as well.
2. when use  ALTERNATE-SERVER Mechanism in turnserver with two turnserver, libnice.a print these log:
STUN demux: OK!
STUN auth error: No message integrity attribute!
STUN transaction retransmitted (timeout 399ms).
STUN transaction retransmitted (timeout 399ms).
STUN demux: OK!
STUN auth error: No message integrity attribute!
STUN demux error: no cookie!
STUN unknown: 0 mandatory attribute(s)!
Received 92-bytes STUN message
 No XOR-MAPPED-ADDRESS: 1
 Mapped address found!
STUN demux error: no cookie!
STUN demux error: no cookie!
STUN transaction retransmitted (timeout 796ms).
STUN demux: OK!
STUN auth error: No message integrity attribute!
STUN transaction retransmitted (timeout 1592ms).
STUN demux: OK!
STUN auth error: No message integrity attribute!

No generate correct SDP info, no relay address info.
Sorry, my English is not very good.

**Comment by jcague** [comment]
can you try using Nicer by setting this attribute in your licode_config.js please?
`config.erizo.useNicer = true;  // default value: false`
Also, please try always to use the template because it will help us trying to reproduce issues.

**Comment by dqgv587** [comment]
Hi, the issue  is caused by libnice. Details as follow:
https://gitlab.freedesktop.org/libnice/libnice/issues/66
