### ISSUE TITLE
Maximum call stack size exceeded on the latest version

### ISSUE THREAD

**Issue by cracker0dks** [lynckia/licode#1358]
Getting this error.

> 2019-02-07 15:26:08.754  - INFO: RoomController - message: processSignaling, clientId: 39d36e40-73fc-4bd1-8f40-006845d8e02b, streamId: 562466573704481860
> [erizo-8f5f336f-8db1-2e39-42e2-c84121f85add] 2019-02-07 15:26:08.757  - INFO: ErizoJSController - message: Process Signaling message, streamId: 562466573704481860, clientId: 39d36e40-73fc-4bd1-8f40-006845d8e02b
> [erizo-8f5f336f-8db1-2e39-42e2-c84121f85add] 2019-02-07 15:26:08,757  - DEBUG [0x7f343172b740] WebRtcConnection - id: 39d36e40-73fc-4bd1-8f40-006845d8e02b_1,  message: Adding remote Candidate, candidate: end, mid: end, sdpMLine: -1
> 2019-02-07 15:26:08,757  - DEBUG [0x7f343172b740] WebRtcConnection - id: 39d36e40-73fc-4bd1-8f40-006845d8e02b_1,  message: All candidates received
> 2019-02-07 15:26:08,757  - DEBUG [0x7f343172b740] LibNiceConnection - id: 39d36e40-73fc-4bd1-8f40-006845d8e02b_1,  message: setting hasReceivedLastCandidate, hasReceived: 1
> 2019-02-07 15:26:11.451  - WARN: EcCloudHandler - message: agent selected timed out trying again, code: 504
> 2019-02-07 15:26:11.480  - ERROR: ErizoAgent - message: error creating ErizoJS, error: RangeError: Maximum call stack size exceeded
>     at Array.find (native)
>     at ErizoList.get firstStopped [as firstStopped] (/opt/licode/erizo_controller/erizoAgent/erizoList.js:38:24)
>     at ErizoList.create (/opt/licode/erizo_controller/erizoAgent/erizoList.js:90:23)
>     at ErizoList.getErizo (/opt/licode/erizo_controller/erizoAgent/erizoList.js:55:14)
>     at ErizoList.getErizo (/opt/licode/erizo_controller/erizoAgent/erizoList.js:56:21)
>     at ErizoList.getErizo (/opt/licode/erizo_controller/erizoAgent/erizoList.js:56:21)
>     at ErizoList.getErizo (/opt/licode/erizo_controller/erizoAgent/erizoList.js:56:21)
>     at ErizoList.getErizo (/opt/licode/erizo_controller/erizoAgent/erizoList.js:56:21)
>     at ErizoList.getErizo (/opt/licode/erizo_controller/erizoAgent/erizoList.js:56:21)
>     at ErizoList.getErizo (/opt/licode/erizo_controller/erizoAgent/erizoList.js:56:21)
> 2019-02-07 15:26:16.452  - WARN: EcCloudHandler - message: agent selected timed out trying again, code: 504
>

**Comment by cracker0dks** [comment]
still getting this error (but only if I run it with more than one thread: MAXPROCESSES>=2 )

**Comment by jcague** [comment]
we need more context, can you please use the Issue template to give us more info?

**Comment by cracker0dks** [comment]
Here you go...

**Steps to reproduce the issue:**
1. Start licode via docker (MAXPROCESSES=2 or more at the licode_config.js)
2. Open two tabs with with the basic example and connect
3. Get this server error

Codebase: 980b0d6032dca67d606ab62d1e906c6486c39ea4 (Latest)

**Comment by cracker0dks** [comment]
resolved the problem. 
I had: `config.erizoAgent.maxProcesses = '2'; ` at my config (value as String), witch was working for some time. After: https://github.com/lynckia/licode/commit/3118a583d4a6532eb2e27ad6942f0d54ed9cbb2a it has to be: `config.erizoAgent.maxProcesses = 2;`
