### ISSUE TITLE
Publish problem on chrome v 72

### ISSUE THREAD

**Issue by ashar02** [lynckia/licode#1363]
On recent release of chrome v 72. Video publishing showing big packet drop. Here is the screenshot of it.
<img width="1664" alt="screen shot 2019-02-19 at 2 45 39 pm" src="https://user-images.githubusercontent.com/1763187/53005643-79b0b880-3455-11e9-9549-0b0bdf2a78fb.png">

**Comment by jcague** [comment]
please use the template to give us more info about the context.

**Comment by ashar02** [comment]
okay let me close it and create one with according to template.
