### ISSUE TITLE
Err: POD document had syntax errors at /usr/bin/pod2man line 71 run patch

### ISSUE THREAD

**Issue by Kozlov-V** [lynckia/licode#137]
When i run install:
`
./licode/scripts/installUbuntuDeps.sh
`
i have error:
`
POD document had syntax errors at /usr/bin/pod2man line 71 run patch
`

**Comment by Meghna08** [comment]
Hey.. We are using Ubuntu version 14.04, and have faced the same issue. Will this only work for version 12.04 or is it some other issue?

**Comment by wgw335363240** [comment]
Year.. I have the same issue.How to resolve?
