### ISSUE TITLE
licode doesn't work with DTLSv1.2 in chrome version 74

### ISSUE THREAD

**Issue by y0zg** [lynckia/licode#1373]
Currently licode isn't adopted to use chrome version 74 and  DTLSv1.2

Please let me know if there are intentions to fix this.

https://groups.google.com/forum/#!searchin/discuss-webrtc/dtls%7Csort:date/discuss-webrtc/yr6gbAgWsKo/9X5vQb8kGAAJ

**Comment by kekkokk** [comment]
how did u tested it? is there any way to force chrome 74 to use DTLS1.2? 'Cause I tried last dev Chrome 74 and connects fine

**Comment by y0zg** [comment]
Checked again, it seems that there is something wrong in my build as openssl version 1.0.1 is used by default , when I install openssl 1.0.2 it started working.
Thank you!

**Comment by dqgv587** [comment]
In my licodeMCU server,  i upgraded licode to pre-v7.8. However, ICE connection can't be established. when call onHandshakeCompleted function, webrtc client didn't send rtppacket. It sent a  Encrypted Alert packet. My openssl's version is 1.0.2j.

**Comment by jcague** [comment]
this should be fixed now
