### ISSUE TITLE
client can't play video

### ISSUE THREAD

**Issue by dqgv587** [lynckia/licode#1383]
Hi, I upgraded licodeMCU server to pre_v7.8. 
There are some problems, details as following:
1. Client publishes the shared screen stream and the subscriber can't play it. In the licode server, i convert publish stream to webm stream (http). I can watch it.
2. Client publishes webcam stream. Subscriber can't play the video, but can hear the sound. In the licode server, i convert publish stream to webm stream (http). I can watch video and hear the sound.

**Comment by jcague** [comment]
please complete the form from the template
