### ISSUE TITLE
Reconnect lost remote's stream which joined when reconnecting

### ISSUE THREAD

**Issue by TopsLuo** [lynckia/licode#1391]
**Description**
see reproduc the issue

**Steps to reproduce the issue:**

1. clientA join room
2. Disconnect the clientA's network，then reconnecting
3. clientB join
4. clientA connect to then network, then reconnect to room
5. clientB can subscribe clientA，but clientA could not receive anything for clientB's information after reconnect

**Comment by YashonNice** [comment]
@TopsLuo Hello, has your issue been resolved?

**Comment by TopsLuo** [comment]
No, I think we need to modify the ErizoController module

**Comment by YashonNice** [comment]
@TopsLuo Thank you for your reply!

I think so too. I have set up a WebRtc project before, and encountered this situation during the reconnection process. I did not solve it later. I think this should be the problem of the Socket.IO room.

Have you changed your plan now?

**Comment by TopsLuo** [comment]
@YashonNice No, I left the job to my colleague

**Comment by YashonNice** [comment]
@TopsLuo okay, thank you.
