### ISSUE TITLE
Publish a standalone erizo package to NPM

### ISSUE THREAD

**Issue by DamonOehlman** [lynckia/licode#14]
Really impressed with the Licode suite of tech. I would ideally love to see erizo published to npm as a standalone module as I think a lot of people would be interested in what you are providing (the code C++ code plus node API).

Happy to take a look at the work involved in getting it to NPM if that helps.

Cheers,
Damon.

**Comment by Vardiak** [comment]
I think you should really reconsider this, it is not believable to copy paste code into a project in 2019...
