### ISSUE TITLE
Frame rate drop in shared screen

### ISSUE THREAD

**Issue by mkhahani** [lynckia/licode#1403]
Today I just updated my production server from v5 to v7. Now users are complaining about poor quality of the shared screen and some have reported that they do not receive the video at all.

I could not reproduce the issue on my local host completely but I see a drop in the frame rate of the shared screen after some minutes. Can any body confirm the issue?

**Comment by mkhahani** [comment]
**Update:** Here's the result of frame rate when subscribing to a shared screen having simulcast enabled on Chrome 73 and 74. The video is almost stopped on Chrome 74:

**Chrome 73**
![image](https://user-images.githubusercontent.com/859377/56810751-4d962700-684c-11e9-877a-22ab67216207.png)

**Chrome 74**
![image](https://user-images.githubusercontent.com/859377/56810759-51c24480-684c-11e9-87f3-c794ea3eb4ad.png)

**Comment by mkhahani** [comment]
**Update:** The quality is fine for 73 until 74 joins and subscribes to the screen. It recovers again after 74 leaves!

![image](https://user-images.githubusercontent.com/859377/56811692-9058fe80-684e-11e9-81a1-d44047399868.png)

**Comment by wolmi** [comment]
+1

I have detected the same, what we see in our logs is a timeout on the keyframes, then the keyframes starts going down and in reverse the NACK goes up

**Comment by lidedongsn** [comment]
see PR #1400

**Comment by mkhahani** [comment]
@lidedongsn Yeah but the PR is not merged yet. Do you know what's preventing it to be merged?

**Comment by lidedongsn** [comment]
@mkhahani  code review

**Comment by lodoyun** [comment]
#1400 fixed this
