### ISSUE TITLE
Why FecReceiverHandler is OutboundHandler

### ISSUE THREAD

**Issue by yuanchao0310** [lynckia/licode#1416]
As my understanding, FecReceiverHandler's job is recovery packet from Red FEC packet.
So this handler should be an Inboundhandler.

Suppose this case: one user publish stream, multi-users subscribe this stream.
in current licode FecReceiverHandler, the red fec packet will be processed multi times. because each outbound hander will do recovery process.

please correct me if my understanding wrong

**Comment by kekkokk** [comment]
Fecreceiverhandler, if I'm not wrong, is a deactivated module since years.

**Comment by yuanchao0310** [comment]
> Fecreceiverhandler, if I'm not wrong, is a deactivated module since years.

OK. Thanks.
I will close it.

**Comment by vpoddubchak** [comment]
Can somebody answer why FEC support was deactivated ?

**Comment by ihorbenko** [comment]
Any update here (see post above)?
