### ISSUE TITLE
H264 simulcast doesn't work well in chrome

### ISSUE THREAD

**Issue by wangbing8895** [lynckia/licode#1422]
I  try h264 simulcast at chrome(75) ,sometimes it can work,but sometimes it doesn't work well !
I used wireshark to grab the packet to observe the ssrc of  video.

**Comment by wangbing8895** [comment]
I also find that VP8 simulcast doesn't work well in chrome(75),why?

**Comment by jcague** [comment]
please, fill in the template to give us more info. Closing in the meantime.
