### ISSUE TITLE
try to start licode meet a problem

### ISSUE THREAD

**Issue by shixiaoxiang** [lynckia/licode#1430]
1.i use docker to run licode 
`MIN_PORT=30000; MAX_PORT=30050; sudo docker run --name licode -p  3000:3000 -p $MIN_PORT-$MAX_PORT:$MIN_PORT-$MAX_PORT/udp -p 3001:3001  -p 8080:8080 -e "MIN_PORT=$MIN_PORT" -e "MAX_PORT=$MAX_PORT" -e "PUBLIC_IP=47.104.106.140" lynckia/licode`
 
it is ok,i think success.but it can not show video when i entry 47.104.106.140:3001 in chrome.  log has no error,why?

my computer camera is ok.

log:
![image](https://user-images.githubusercontent.com/15920209/61037560-e2490380-a3fd-11e9-902f-bd4d43bb1af0.png)

chrome:
![image](https://user-images.githubusercontent.com/15920209/61037576-ed039880-a3fd-11e9-98c2-8b1cb8b8aa2f.png)
![image](https://user-images.githubusercontent.com/15920209/61037583-f4c33d00-a3fd-11e9-8733-e0c87ac1989b.png)

**Comment by Jacky-LinPeng** [comment]
我也遇到同样的问题 你是怎么解决的？
