### ISSUE TITLE
Basic example fails if a room uses more than one Erizo

### ISSUE THREAD

**Issue by nvazquezg** [lynckia/licode#1432]
**Description**

If Licode is configured in a way that allows a room to use more than one Erizo, the subscription to remote streams fails most of the time.

**Steps to reproduce the issue:**
1. Configure licode to allow rooms to use more than one Erizo. For example, in licode_config.js:
```
config.erizoController.maxErizosUsedByRoom = 100;  // default value: 100
config.erizoAgent.maxProcesses    = 2; // default value: 1
```
2. Start Licode and Basic Example:
```
$ ./scripts/initLicode.sh
$ ./scripts/initBasicExample.sh
```
3. Connect to Licode Basic Example using two chrome browser windows with a webcam available. By default: http://localhost:3001/

**Describe the results you received:**
The first browser only shows one video.
The second browser shows two videos (sometimes one).

**Describe the results you expected:**
The first browser shows two videos.
The second browser must show two videos.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens every time.
When it fails, a message is shown this message in the console:
```
WARNING:  processAnswer discarding old sdp, sessionVersion: 0, latestSessionVersion: 0
```
If we change `maxProcesses` to its default value (1) or `maxErizosUsedByRoom` to 1 it works every time.
In versión pre-v7.8 this use case worked.

**Licode commit/release where the issue is happening**
pre-v7.11: 245fb64c0ecdea0f6f56a15a2020881c2285ed9b 

**Additional environment details (Local, AWS, Docker, etc.):**
Same behaviour in Local and using official docker image `lynckia/licode:245fb64`.
Chrome 75.

**Comment by ashar02** [comment]
@jcague I also tested the latest code till commit #1429 a moment ago. When I changed the default value of either config.erizoAgent.maxProcesses or config.erizoAgent.prerunProcesses I also started facing same problem as mentioned in this issue. Most of the time subscription failed. Can you please look into this?

**Comment by ashar02** [comment]
@lodoyun can you please look into this issue?

**Comment by jcague** [comment]
@ashar02 I think I found the issue you are having with the latest versions, can you test it with #1439 please?

**Comment by ashar02** [comment]
Okay let me test and get back to you soon!!

**Comment by ashar02** [comment]
Yes fixed on my environment as well. Great Job!!
