### ISSUE TITLE
Unable to receive more than 300 kbps in licode base_example

### ISSUE THREAD

**Issue by vpoddubchak** [lynckia/licode#1434]
**Description**
Can't get receive bandwidth more that 300 kbps in licode's example.

**Steps to reproduce the issue:**
1. Run docker licode:staging
2. Change values in licode/scripts/licode_default.js: defaultVideoBW = 800; maxVideoBW = 800;
3. Commit and restart container
4. Open page http://localhost:3001/ to start publishing
5. Open chrome://webrtc-internals to check publishing bitrate: it is 800kbps
6. Open another page: http://localhost:3001/?onlySubscribe=true and press Start to subscribe to the stream
7. check webrtc-internals - publishing BW drop to 300kbps:
![webrtc-internals-800to300](https://user-images.githubusercontent.com/6253301/61536602-aafdd680-aa3d-11e9-95f6-d8d1aa002c24.png)
8. check http://localhost:3001/quality_layers.html to see limit in 300kbps on subscriber side:
![quality_layers_300_limit](https://user-images.githubusercontent.com/6253301/61536637-be10a680-aa3d-11e9-8813-9dab98cdd211.png)

**Describe the results you expected:**
I expect to see 800 kbps stream on receiver side because there:
https://github.com/lynckia/licode/blob/master/scripts/licode_default.js#L54
_Default and max video bandwidth parameters to be used by clients for both published and subscribed streams_

But looks like it is hard-coded somewhere.

**Comment by ashar02** [comment]
I am also facing same!!

**Comment by jcague** [comment]
I found the issue, as @vpoddubchak suggests there is a default max video bw hardcoded to 300 in various places of our codebase, we should remove that limit or put a much higher one.

**Comment by jcague** [comment]
This is a quick fix #1440
