### ISSUE TITLE
when publishing rtsp giving error 

### ISSUE THREAD

**Issue by peererror** [lynckia/licode#1446]
**Description**
when publishing external rtsp link from licode giving error time out . When turn on the logging for external output we see that ffmpeg is trying to connect wrong url please see the attached log on this link https://pastebin.com/Vxk5LW3b
**Describe the results you received:**

we can see the ffmpeg is trying to receive wrong file url which is like this :
{ rpcExc.publish(message.replyTo, { data: result, corrID: message.corrID, type }); } 

instead of rtsp you url .

**Describe the results you expected:**
ffmpeg will play the rtsp url

**Comment by TopsLuo** [comment]
I fixed this problem(but has another problem):
--- a/erizo_controller/erizoController/roomController.js
+++ b/erizo_controller/erizoController/roomController.js
@@ -132,7 +132,7 @@ exports.RoomController = (spec) => {
 
       getErizoJS((erizoId) => {
                 // then we call its addPublisher method.
-        const args = [publisherId, url];
+        const args = [erizoControllerId, publisherId, url]

**Comment by peererror** [comment]
@TopsLuo  your code the solves the issue for wrong url  but after that licode crashes randomly and I am only seeing black video of rtsp. Are you getting the same issue like mine 
@jcague  @lodoyun  
please help to fix this issue . I have to publish rtsp camera stream in licode room with other participants any kind of hints to solve this issue will also help .

**Comment by TopsLuo** [comment]
You cant display your local rtsp stream in a video element out of the box on the client.But you can subscribe publisher's rtsp and display

diff --git a/erizo/src/erizo/media/ExternalInput.cpp b/erizo/src/erizo/media/ExternalInput.cpp
index 5933a14..33fa052 100644
--- a/erizo/src/erizo/media/ExternalInput.cpp
+++ b/erizo/src/erizo/media/ExternalInput.cpp
@@ -133,11 +133,11 @@ int ExternalInput::init() {
 
 
     om.processorType = RTP_ONLY;
    om.videoCodec.codec = VIDEO_CODEC_VP8;
//    om.videoCodec.codec = VIDEO_CODEC_H264;
     om.videoCodec.bitRate = 1000000;
//    om.videoCodec.width = 640;
//    om.videoCodec.height = 480;
//    om.videoCodec.frameRate = 20;
    om.videoCodec.width = context_->streams[video_stream_index_]->codec->width;
    om.videoCodec.height = context_->streams[video_stream_index_]->codec->height;
    om.videoCodec.frameRate = context_->streams[video_stream_index_]->avg_frame_rate.num / context_->streams[video_stream_index_]->avg_frame_rate.den;
     om.hasVideo = true;
 
     om.hasAudio = false;

**Comment by peererror** [comment]
@TopsLuo I am seeing black frames of rtsp on subscriber end but I can hear audio  of rtsp video .
