### ISSUE TITLE
Run ErizoController via HTTPS for chrome update to version 36

### ISSUE THREAD

**Issue by fastfading** [lynckia/licode#147]
As Chrome blocks non-SSL websocket connection over HTTPS
I changed some code  in erizoController 
var https = require('https');
var fs = require("fs");
var options = {
    key: fs.readFileSync('cert/key.pem').toString(),
    cert: fs.readFileSync('cert/cert.pem').toString()  
};

var server = https.createServer(options);

  and set config in licode_configure  
config.erizoController.ssl = true

however I get ice failed  later,  

13 2014-08-01 21:40:30,088 - WARN: NiceConnection - Ice Failed 0x3c75ba0
https://groups.google.com/forum/#!topic/lynckia/S1odJXkRx1k

there is similar issue before, and it is not solved  ,  so it should not be closed.

**Comment by andresrivas1506** [comment]
@jcague Some tutorial for it?

> I'd suggest to use NGINX to proxy WS connections via secure connections. This configuration is currently working in production environments.
