### ISSUE TITLE
The code below is write?

### ISSUE THREAD

**Issue by yokots** [lynckia/licode#1481]
https://github.com/lynckia/licode/blob/458edbc532f58d9b062d396e4a6ee86be9ad5a8e/erizo_controller/common/semanticSdp/SimulcastInfo.js#L17
```js
cloned.addSimulcastAlternativeStreams(DirectionWay.SEND, alternatives);
```
https://github.com/lynckia/licode/blob/458edbc532f58d9b062d396e4a6ee86be9ad5a8e/erizo_controller/common/semanticSdp/SimulcastInfo.js#L24
```js
cloned.addSimulcastAlternativeStreams(DirectionWay.RECV, alternatives);
```

**Comment by jcague** [comment]
good catch @yokots thanks a lot!
