### ISSUE TITLE
"brew install rabbitmq mongodb" ERROR

### ISSUE THREAD

**Issue by ihoudf** [lynckia/licode#1491]
**Hi, when I run "./scripts/installMacDeps.sh" On Mac OS X,there is a question like this.**

`
Error: No available formula with the name "mongodb" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
These similarly named formulae were found:
mongodb/brew/mongodb-community ✔         mongodb/brew/mongodb-community@3.4
mongodb/brew/mongodb-community-shell     mongodb/brew/mongodb-community@3.6
mongodb/brew/mongodb-community@3.2       mongodb/brew/mongodb-community@4.0
To install one of them, run (for example):
  brew install mongodb/brew/mongodb-community ✔
==> Searching taps...
==> Searching taps on GitHub...
`

**I try to use "mongodb-community " to replace  "rabbitmq mongodb",but there is another question when I run "./scripts/initLicode.sh" :**

`rabbitmq-server: command not found`

**how should I deel with this problem**

**Comment by jcague** [comment]
I needed more info, please follow the Issue template we created to give us enough info to help you (version of MacOS, commit, etc.)
