### ISSUE TITLE
NodeJS version

### ISSUE THREAD

**Issue by ashar02** [lynckia/licode#1492]
You people should consider to update the NodeJS version use by this project. As it goes quite outdated now (v 6.x). This will also reduce the installation time as well from source code. @jcague

**Comment by jcague** [comment]
yes, you are right, we have it in mind. It used to be a bit complex in the past because we have the NodeJS addon and it usually entails some change. But it worths spending some time investigating. Thanks!

**Comment by jcague** [comment]
this is actually the EOL: 2019-04-30 (https://github.com/nodejs/Release)

**Comment by ashar02** [comment]
Okay!!
