### ISSUE TITLE
MongoError when nuve update rooms data

### ISSUE THREAD

**Issue by SPccman** [lynckia/licode#1495]
**Description**

**Steps to reproduce the issue:**
1. when i kill erizoController.js,  MongoError occured when nuve update rooms data。

**Describe the results you received:**
source code position is  nuve/nuveAPI/mdb/roomRegistry.js  line 92。 
error log was "MongoError: the update operation document must contain atomic operators". i built licode from source,mongojs 3.0.0 was installed by default.  when i install mongojs version 2.6.0, it works without error.

**Comment by lodoyun** [comment]
Thanks for the report. Nuve is not compatible with mongojs 3.0. For now we're forcing 2.6 -> Fix in #1496

**Comment by SPccman** [comment]
ok
