### ISSUE TITLE
The stream is subscribed, stream-data event not triggered

### ISSUE THREAD

**Issue by YashonNice** [lynckia/licode#1501]
The stream is subscribed, but after using localstream. Senddata(), the stream data that localstream listens for is not received a message

Can you help me, thank you

**Comment by jcague** [comment]
could you fill in the template to give us more context please?

**Comment by YashonNice** [comment]
@jcague  Thank you for your reply. The problem has been found. It should be a licode bug. By the way, I built it with docker

I try to find the [onmessage] event in erizo.js, and print it in the browser console, and then use the localstream.senddata function to send it, so that I can receive the message, so I locate [ondatastream] about 3557 lines, so that I can also receive the message, but I can't receive the message in localstream.addeventlistener ("stream. Data"), so I will The stream monitoring has changed to a room monitoring event, as follows:

```javascript
r.on("onDataStream", l.bind(null,
function(a) {
	var b = k.get(a.id);
	a = Object(c.f)({
		type: "stream-data",
		msg: a.msg,
		stream: b
	});
        //This is the original. b is the object of the listening stream
	//b.dispatchEvent(a)
        //This is my modified one. I gave the monitoring task to the room object, which is u
        u.dispatchEvent(a)
}));
```

So the way I use it now becomes:
```javascript
room.addEventListener("stream-data", function(evt){
	console.log("This is OK, Receive message:" + evt.msg);
});
```

**Comment by jcague** [comment]
it looks like you are sending data from your localStream and want to receive it through the same localStream? I don't know about your scenario but Licode's data messages were not implemented for such case, I'm sorry.

**Comment by YashonNice** [comment]
@jcague It's because the local stream can't be received, so it's changed to this way
