### ISSUE TITLE
installErizo.sh build script , npm errors on Ubuntu 16.04

### ISSUE THREAD

**Issue by Sleepingbug** [lynckia/licode#1519]
I compile the code according to the guidelines of this URL：
https://licode.readthedocs.io/en/master/from_source/
(same as http://lynckia.com/licode/install.html )

After some efforts, many problems were solved．
Operating environment：
Ubuntu 16.04 64-bit
node -v: v12.12.0
npm -v: 6.13.2
gcc version 5.5.0

Step1:./scripts/installUbuntuDeps.sh
There are some warnings:

`npm WARN eslint-plugin-eslint-plugin@2.1.0 requires a peer of eslint@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

I know the last two warnings can be ignored.
I don`t know the consequences of the first warning.
But I did not try to resolve these warnings.
Because the result is no error.

-----------
Step2:./scripts/installNuve.sh

`[nuve] Done, node_modules installed
mkdir: cannot create directory '../dist': File exists
mkdir: cannot create directory '../build': File exists
mkdir: cannot create directory '../dist': File exists
mkdir: cannot create directory '../build': File exists
../lib/xmlhttprequest.js:11 (JSC_PARSE_ERROR)
Parse error. illegal use of unknown JSDoc tag "contributor"; ignoring it
 * @contributor David Ellis <d.f.ellis@ieee.org>
   ^

[nuve] Done, nuve.js compiled`
...

It seems no problem, and then I continue

--------------
Step3:./scripts/installErizo.sh

The process is OK, but some errors appear in the end

`Installing erizoAPI...
Checking dir /home/howard/licode-all/licode-master/build/libdeps/nvm
Running nvm
Found '/home/howard/licode-all/licode-master/.nvmrc' with version <12.13.0>
Now using node v12.13.0 (npm v6.12.0)

> licode-erizo-api@0.1.0 preinstall /home/howard/licode-all/licode-master/erizoAPI
> ./lint.sh

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! licode-erizo-api@0.1.0 preinstall: `./lint.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the licode-erizo-api@0.1.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-07T06_12_47_118Z-debug.log`

What should I do? how to solve these problems ?
Or, as said above, it is probably not a problem? 
Because i keep going down to excute
./scripts/installBasicExample.sh
no errors occurred

**Comment by Sleepingbug** [comment]
----------
log:
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/howard/licode-all/licode-master/build/libdeps/nvm/versions/node/v12.13.0/bin/node',
1 verbose cli   '/home/howard/licode-all/licode-master/build/libdeps/nvm/versions/node/v12.13.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--unsafe-perm'
1 verbose cli ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose npm-session 220cd6de00bf1a64
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall licode-erizo-api@0.1.0
7 info lifecycle licode-erizo-api@0.1.0~preinstall: licode-erizo-api@0.1.0
8 verbose lifecycle licode-erizo-api@0.1.0~preinstall: unsafe-perm in lifecycle true
9 verbose lifecycle licode-erizo-api@0.1.0~preinstall: PATH: /home/howard/licode-all/licode-master/build/libdeps/nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/howard/licode-all/licode-master/erizoAPI/node_modules/.bin:/home/howard/licode-all/licode-master/build/libdeps/nvm/versions/node/v12.13.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle licode-erizo-api@0.1.0~preinstall: CWD: /home/howard/licode-all/licode-master/erizoAPI
11 silly lifecycle licode-erizo-api@0.1.0~preinstall: Args: [ '-c', './lint.sh' ]
12 silly lifecycle licode-erizo-api@0.1.0~preinstall: Returned: code: 1  signal: null
13 info lifecycle licode-erizo-api@0.1.0~preinstall: Failed to exec preinstall script
14 timing stage:rollbackFailedOptional Completed in 1ms
15 timing stage:runTopLevelLifecycles Completed in 75ms
16 verbose stack Error: licode-erizo-api@0.1.0 preinstall: `./lint.sh`
16 verbose stack Exit status 1
16 verbose stack     at EventEmitter.<anonymous> (/home/howard/licode-all/licode-master/build/libdeps/nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
16 verbose stack     at EventEmitter.emit (events.js:210:5)
16 verbose stack     at ChildProcess.<anonymous> (/home/howard/licode-all/licode-master/build/libdeps/nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
16 verbose stack     at ChildProcess.emit (events.js:210:5)
16 verbose stack     at maybeClose (internal/child_process.js:1021:16)
16 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
17 verbose pkgid licode-erizo-api@0.1.0
18 verbose cwd /home/howard/licode-all/licode-master/erizoAPI
19 verbose Linux 4.15.0-72-generic
20 verbose argv "/home/howard/licode-all/licode-master/build/libdeps/nvm/versions/node/v12.13.0/bin/node" "/home/howard/licode-all/licode-master/build/libdeps/nvm/versions/node/v12.13.0/bin/npm" "install" "--unsafe-perm"
21 verbose node v12.13.0
22 verbose npm  v6.12.0
23 error code ELIFECYCLE
24 error errno 1
25 error licode-erizo-api@0.1.0 preinstall: `./lint.sh`
25 error Exit status 1
26 error Failed at the licode-erizo-api@0.1.0 preinstall script.
26 error This is probably not a problem with npm. There is likely additional logging output above.
27 verbose exit [ 1, true ]`

**Comment by Sleepingbug** [comment]
Failed to exec preinstall script

**Comment by Sleepingbug** [comment]
T_T... i've tried for a week but no results

**Comment by lodoyun** [comment]
duplicated #1520

**Comment by Sleepingbug** [comment]
@lodoyun Thank you very much
