### ISSUE TITLE
basic example is get local media error 

### ISSUE THREAD

**Issue by junwangustc** [lynckia/licode#1522]
![Lark20191208100030](https://user-images.githubusercontent.com/20556297/70383020-9a74db00-19a1-11ea-8ea0-78a786578917.png)
who can help me sovle it ,when I connect to myIP:3001 with the chrome ,it returns the error ,thanks for who knew the answer

**Comment by vpoddubchak** [comment]
Looks like you do not have properly installed webcam. 
Try this demo: https://chotis2.dit.upm.es/
If it will work, then you should check such points:
- Make sure your camera does not busy by another app
- Do you allow camera for localhost when it asked ? Check Chrome's settings to be sure
- Do you use http (without S) for your localhost ?
- Did you try in Mozilla ? it sometimes has less restrictions about devices

**Comment by Sleepingbug** [comment]
use https instead of http
