### ISSUE TITLE
not work in chrome.  how to configure it to use wss ?

### ISSUE THREAD

**Issue by Sleepingbug** [lynckia/licode#1526]
It doesn't work in the Version 79.0.3945.79 (64-bit) of chrome.

first of all, i know http cannot access the camera in new version chrome. 
i try to use https.
It seems to be caused by using https but not configured wss, I don't know how to configure wss.

details as below:

my computer os is : Ubuntu 16.04 64-bit.
LAN IP is 192.168.1.172

Step1: execute ./scripts/initLicode.sh
and execute ./scripts/initBasicExample.sh

Step2: visit https://192.168.1.172:3004/ and allow it to use camera and microphone.
Step3: click "Test Connection" 
then I see logs in chrome's console:

connection_test.js:35 eyJ0b2tlbklkIjoiNWRmNDk2OWM3NTkzMWUwYzYwZDc2NzMzIiwiaG9zdCI6IjE5Mi4xNjguMS4xNzI6ODA4MCIsInNlY3VyZSI6ZmFsc2UsInNpZ25hdHVyZSI6IlkyRTJPRGRpTlRSa016ZzVZV05rWW1JMU9HSTBaR05rTVdWak9URXhNMlV4TkdFM1pUVXhZUT09In0=
erizo.js:29 INFO:  Requested access to local media
erizo.js:29 DEBUG:  Calling getUserMedia with config Object
erizo.js:29 INFO:  User has granted access to local media.
erizo.js:338 Mixed Content: The page at 'https://192.168.1.172:3004/connection_test.html' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://192.168.1.172:8080/socket.io/?EIO=3&transport=websocket'. This request has been blocked; this endpoint must be available over WSS.
b.doOpen @ erizo.js:338
erizo.js:29 INFO:  Error triggering event: access-accepted, error: TypeError: Cannot read property 'onclose' of undefined
erizo.js:29 INFO:  getTracks MediaStreamTrack
erizo.js:29 INFO:  getTracks MediaStreamTrack

**Comment by vpoddubchak** [comment]
Try to change `config.erizoController.ssl = false;` to `true`
there: https://github.com/lynckia/licode/blob/master/scripts/licode_default.js#L69

**Comment by Sleepingbug** [comment]
> Try to change `config.erizoController.ssl = false;` to `true`
> there: https://github.com/lynckia/licode/blob/master/scripts/licode_default.js#L69

I tried,  same problem

**Comment by dengliang2008** [comment]
> > Try to change `config.erizoController.ssl = false;` to `true`
> > there: https://github.com/lynckia/licode/blob/master/scripts/licode_default.js#L69
> 
> I tried, same problem.
> it seems that erizo.js needs to be modified

After changed config.erizoController.ssl=true and config.erizoController.listen_ssl=true.You need to run './script/installNuve.sh' again.

**Comment by Sleepingbug** [comment]
> > > Try to change `config.erizoController.ssl = false;` to `true`
> > > there: https://github.com/lynckia/licode/blob/master/scripts/licode_default.js#L69
> > 
> > 
> > I tried, same problem.
> > it seems that erizo.js needs to be modified
> 
> After changed config.erizoController.ssl=true and config.erizoController.listen_ssl=true.You need to run './script/installNuve.sh' again.

Thanks ! I'll try again
