### ISSUE TITLE
Can't increase sending BW after limiting of it.

### ISSUE THREAD

**Issue by vpoddubchak** [lynckia/licode#1528]
**Description**

In our app we allow to limit publishing BW during session. We use **updateConfiguration** method with parameter **maxVideoBW** for it. But after limiting it to lower bandwidth, it can't be restored to higher bandwidth. Instead of it audio bandwidth is going Up. 

**Steps to reproduce the issue:**
1. Simulcast is 2 layers, codecs: VP8, OPUS
2. Connect to room by one publisher with BW = 512kb 
3. Limit BW to 128: `localstream.updateConfiguration({ maxVideoBW: 128 });`
4. Check webrtc://chrome-internals - bitrade droped to 128
5. Limit BW to 512: `localstream.updateConfiguration({ maxVideoBW: 512 });`
6. Check webrtc://chrome-internals: video BW is still 128, audio BW increased. (see attach)

Note: reproduces only with simulcast.
![video](https://user-images.githubusercontent.com/6253301/71515219-dcab8100-28aa-11ea-82b1-e2e2f12306fb.png)
![audio](https://user-images.githubusercontent.com/6253301/71515220-dcab8100-28aa-11ea-806f-19429b64e2ac.png)

**Comment by vpoddubchak** [comment]
I have reproduced it with pure licode example in docker:
1. Run docker: `MIN_PORT=30000; MAX_PORT=30150; sudo docker run --name licode -p 3000:3000 -p $MIN_PORT-$MAX_PORT:$MIN_PORT-$MAX_PORT/udp -p 3001:3001 -p 3004:3004 -p 8080:8080 -e "MIN_PORT=$MIN_PORT" -e "MAX_PORT=$MAX_PORT" -e "PUBLIC_IP=<yourIP>" lynckia/licode:develop`
2. Configure nginx to allow ssl connection: http://lynckia.com/licode/nginx-dep.html
3. Open page in Chrome 79: https://your-domain.com/?simulcast=true
4. Pay attention on Audio bitsSentPerSecond and Video bitsSentPerSecond in chrome://webrtc-internals. They both ~150 kbps.
![simulcast_150](https://user-images.githubusercontent.com/6253301/71576584-bdeef980-2af9-11ea-9e34-3d7c8acf14ed.png)

Expected result: Video ~300kbps, Audio ~24kbps

Note: it is OK if do not use simulcast.

**Comment by vpoddubchak** [comment]
I think this is a reason:
https://bugs.chromium.org/p/chromium/issues/detail?id=1002875

Can it be workaround-ed in licode ?

**Comment by kekkokk** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1002875#c31

**Comment by vpoddubchak** [comment]
Looks like it has been fixed in Chrome. I tested it with Chrome v80 dev. And it does not reproduce there.

**Comment by jcague** [comment]
@vpoddubchak @kekkokk is there something we can do before Chrome v80 to avoid or limit this issue in Licode?

**Comment by jcague** [comment]
I've been reading the threads and it looks like @kekkokk implemented a workaround to fix the issue in the meantime, am I right? This is the code you had:
```js
  if ('RTCRtpSender' in window && 'setParameters' in window.RTCRtpSender.prototype) {
    const sender = pc.getSenders()[0];
    const parameters = sender.getParameters();
    if (!parameters.encodings) {
      parameters.encodings = [{}];
    }
    parameters.encodings[0].maxBitrate = 32000;
    sender.setParameters(parameters);
  }
```

**Comment by kekkokk** [comment]
exactly. I'm sorry I can't do a pr but i rewrote completely the clients stack based on the engine instead of the name (see new edge based on blink etc.) and where possible I'm using the transceivers.
But with this fix you will not suffer from this behavior anymore. just set this after the addStream and be sure to do this for the audio sender and not the pc.getSenders()[0], which was only an example.
Meanwhile I suggest you to check or disable the simulcast in FF since from the current version (72), it breaks the sdps since they are now moving from spec 03 to spec 04 of the [rfc](https://datatracker.ietf.org/doc/draft-ietf-mmusic-sdp-simulcast/)

**Comment by vpoddubchak** [comment]
We tried this workaround but without success:
`sender.getParameters()` returns empty array, so we have to add something to it. 
Then we set maxBitrate and call `sender.setParameters(parameters)` which causes exception: 
`Read-only field modified in setParameters()`

Here is our code:
```
export const limitAudioBitrate = (stream) => {
  if ('RTCRtpSender' in window && 'setParameters' in window.RTCRtpSender.prototype) {
    const pc = get(stream, 'pc.stack.peerConnection', null);
    if (!pc) return;
    const [sender] = pc.getSenders();
    if (!sender) return;
    const parameters = sender.getParameters();
    if (!parameters.encodings || !parameters.encodings.length) {
      parameters.encodings = [{}];
    }
    parameters.encodings[0].maxBitrate = 32000;
    sender.setParameters(parameters);
  }
};
```

**Comment by jcague** [comment]
@vpoddubchak this issue should be fixed in Chrome 79 according to Google so we wouldn't need to implement the workaround anymore in new versions of Chrome.
