### ISSUE TITLE
Git master code run ./installErizo.sh fail.

### ISSUE THREAD

**Issue by dengliang2008** [lynckia/licode#1530]
1.New Ubuntu 16.04.6 LTS OS
2.Checkout master source from git server.
3.Run 'installUbuntuDeps.sh','installNuve.sh' success.
4.Run 'installErizo.sh' fail as following error msg:
ERROR: bzip2/1.0.8: Error in package_info() method, line 57
        self.cpp_info.names["pkg_config"] = "bzip2"
        TypeError: '_CppInfo' object does not support item assignment

**Comment by vpoddubchak** [comment]
We fixed it by changing of **conan** version from **1.18.5** to **1.21** there: 
https://github.com/lynckia/licode/blob/master/scripts/installUbuntuDeps.sh#L91

**Comment by dengliang2008** [comment]
> We fixed it by changing of **conan** version from **1.18.5** to **1.21** there:
> https://github.com/lynckia/licode/blob/master/scripts/installUbuntuDeps.sh#L91

Thanks，that's working.
