### ISSUE TITLE
ICE Lite Implementation

### ISSUE THREAD

**Issue by SPccman** [lynckia/licode#1546]
Will nICEr support Lite Implementation?

**Comment by jcague** [comment]
nICEr support more complex ICE scenarios than ICE lite, which is good for more cases, why would you need ICE Lite instead?

**Comment by SPccman** [comment]
If server is on a public network. I think Lite maybe better. Because Lite only need host ip and  don't need to perform connectivity checks. I think it is faster.  This is only a suggestion.

**Comment by jcague** [comment]
AFAIK the server still needs to answer STUN requests to know the other peer's IP, but that's true that there will be fewer checks. Anyway, the improvement won't be so important to add support for it for now. Thanks for the suggestion anyway!
