### ISSUE TITLE
Problem with installUbuntuDeps.sh

### ISSUE THREAD

**Issue by davidguv** [lynckia/licode#1575]
Problem using [installUbuntuDeps.sh](https://github.com/lynckia/licode/blob/master/scripts/installUbuntuDeps.sh#L132), error in command to download opus-1.1

Error in command     `curl -OL http://downloads.xiph.org/releases/opus/opus-1.1.tar.gz`

The site is down for several days.
http://downloads.xiph.org/releases/opus/opus-1.1.tar.gz

Alternative download?
https://ftp.osuosl.org/pub/xiph/releases/opus?

**Steps to reproduce the issue:**
1. Execute ./installUbuntuDeps.sh
2.
3.

**Additional environment details (Local, AWS, Docker, etc.):**
Local Ubuntu 16.04

**Comment by jcague** [comment]
👍  I think we can use that URL as a backup until we know what happens to the official site.
