### ISSUE TITLE
Firefox - SDP configuration, remote  stream subscription failure 

### ISSUE THREAD

**Issue by chesky18** [lynckia/licode#1577]
- If publisher (Chrome) is publishing screen or video, firefox is has issue with SDP response configuration. Issueseems to be BaseStack.js, following code does not work:
let direction = Direction.reverse('sendrecv');
    if (numberOfRemoteMedias > 0 && numberOfLocalMedias > 0) {
      direction = Direction.reverse('sendrecv');
    } else if (numberOfRemoteMedias > 0 && numberOfLocalMedias === 0) {
      direction = Direction.reverse('recvonly');
    } else if (numberOfRemoteMedias === 0 && numberOfLocalMedias > 0) {
      direction = Direction.reverse('sendonly');
    } else {
      direction = Direction.reverse('inactive');
    }

After changing the code to following, it seems to work:
let direction = Direction.reverse(Direction.SENDRECV);
    if (numberOfRemoteMedias > 0 && numberOfLocalMedias > 0) {
      direction = Direction.reverse(Direction.SENDRECV);
    } else if (numberOfRemoteMedias > 0 && numberOfLocalMedias === 0) {
      direction = Direction.reverse(Direction.SENDONLY);
    } else if (numberOfRemoteMedias === 0 && numberOfLocalMedias > 0) {
      direction = Direction.reverse(Direction.RECVONLY);
    } else {
      direction = Direction.reverse(Direction.INACTIVE);
    }

**Comment by david-morales** [comment]
I can reproduce the issue also with Safari
