### ISSUE TITLE
Multi-NIC  cause   Crash

### ISSUE THREAD

**Issue by QuanjieDeng** [lynckia/licode#1584]
**Description**
    @jcague  About  recently time,I  put some issues  about ErioJS's crash,In my environment it crash every time, Im run  my licode  by source code  not docker.
   i get the same err at nICEr  lib，the crash  function is "nr_stun_client_send_request",Today i open the  nICEr’log，I find it, The ICE process try  send msg to a socket already freed.
  There  two NIC  in server , When the  pairs  already selected, the   left still  Sending check request,but the socket is  freed. So  i down  one  of   NIC , the  ErioJS crash  not happen,
I  think it’s bug，im  trying  fix  it, but  this is necessary to let you know.

**Steps to reproduce the issue:**
1.IOS client  join room
2.ErioJS crash

**Licode commit/release where the issue is happening**
Commit [8a0aeb8d1d....](https://github.com/lynckia/licode/commit/8a0aeb8d1d93af0365e6c0d3dddda725c50ad4b5)

**Comment by vpoddubchak** [comment]
Is it the same issue: https://github.com/lynckia/licode/issues/1512 ?

BTW, how do you manage to see nICEr log ? can you give instruction how to do that ?

**Comment by jcague** [comment]
thanks for the info @QuanjieDeng , it will be very interesting to see your advances! I guess this has happened to more people before and it is the reason by which it is better to set the network interface in Erizo's config.

**Comment by QuanjieDeng** [comment]
> Is it the same issue: #1512 ?
> 
> BTW, how do you manage to see nICEr log ? can you give instruction how to do that ?

My method is not very standardized，In the  "NicerConnection::initializeGlobals()",it  set  thr r_log's  options，but  it work，Emergency i   modify  the funtion “r_log” in  r_log.c  file,like this  
`
int r_log(int facility,int level,const char *format,...)
  {
    #if  0
    va_list ap;

    va_start(ap,format);
    
    r_vlog(facility,level,format,ap);
    va_end(ap);
    #endif

    //---
    printf("---level:%d------\r\n",level);
    va_list arg;
    va_start(arg, format);
    vprintf(format, arg);
    va_end(arg);
    printf("---------\r\n");

    //---

    return(0);
  }
`

then   rebuild  the   eriojs  

`
./scripts/installErizo.sh   -e  
`
the   nICEr's  log  whill show  in the   eriojs‘s  log  file

**Comment by QuanjieDeng** [comment]
> thanks for the info @QuanjieDeng , it will be very interesting to see your advances! I guess this has happened to more people before and it is the reason by which it is better to set the network interface in Erizo's config.

Do you  men the   option  flow?
`
config.erizoAgent.publicIP = ''; //default value: ''
config.erizoAgent.networkinterface = 'enp0s3'; //default value: ''
`
This is  my config, but  it whill crash also,Only when i  down NIC and  left    only one,it  ok,
So  i think   the   option not the key!

**Comment by jcague** [comment]
The config setting we change is `config.erizo.networkinterface`.

**Comment by QuanjieDeng** [comment]
@jcague  This also solved the problem I encountered，Maybe I took a detour，But I think this should be a place for improvement
