### ISSUE TITLE
NiceR Issue

### ISSUE THREAD

**Issue by sebastianfelipe** [lynckia/licode#1618]
**Description**
Commits before libnice removal, works perfectly. But after that, every ICE connection is lost, is disconnected, it cannot be possible initiate any connection, nor WebRTC, nor data only. Nothing.

Can you check if everything is working well please? Or just add some licode example config, because I have the licode_default and from that commit an on it doesn't work well anymore.

I have tried with Ubuntu directly, and commonly with Docker.

**Comment by dolevu** [comment]
I have been having the same problem, and still haven't figured out any workaround yet.

**Comment by QuanjieDeng** [comment]
You should provide information on the scene，like   ErioJs's log and your step

**Comment by lodoyun** [comment]
We have been using NiceR in production for over 2 years now with good results. If you are still experiencing this issue, please fill in the issue report template.
