### ISSUE TITLE
Subscribed video is not shown when running basic example of http://localhost:3001/connection_test.html

### ISSUE THREAD

**Issue by jessin20161124** [lynckia/licode#1624]
I open two chrome tab  with the same url of connection_test.html. But Subscribed video is not shown.The detail console log of chrome is as follows :

DEBUG:  (ErizoConnection) message: Adding stream to Connection, connectionId: 7c933682-4d79-436d-aae0-15d411b3adc4_8fab3146-7425-afa5-2372-1037d915b013_1, sessionId: 104, qualityLevel: good, erizoId: 8fab3146-7425-afa5-2372-1037d915b013, 
erizo.js:1 DEBUG:  (PeerConnectionFsm) message: onBeforeAddStream, from: initial, to: initial
erizo.js:1 INFO:  (PeerConnectionFsm) message: onTransition, transition: add-stream, from: initial, to: initial
erizo.js:1 DEBUG:  (PeerConnectionFsm) message: onBeforeCreateOffer, from: initial, to: stable
erizo.js:1 INFO:  (PeerConnectionFsm) message: onTransition, transition: error, from: initial, to: failed
erizo.js:1 WARNING:  (PeerConnectionFsm) message: Error Transition Failed, message: in protectedCreateOffer-createOffer, error: TypeError: Cannot read property 'get' of undefined, from: initial, to: failed, printing history
erizo.js:1 WARNING:  (PeerConnectionFsm) message: Error Transition Failed continuation, item: {"from":"none","to":"initial","transition":"init"}
erizo.js:1 WARNING:  (PeerConnectionFsm) message: Error Transition Failed continuation, item: {"from":"initial","to":"initial","transition":"add-stream"}
erizo.js:1 WARNING:  (PeerConnectionFsm) message: Error Transition Failed continuation, item: {"from":"initial","to":"failed","transition":"error"}

**Comment by lodoyun** [comment]
Please use the issue template. We need that information to diagnose the problem
