### ISSUE TITLE
'overflowchanged' event is deprecated and may be removed. Please do not use it.

### ISSUE THREAD

**Issue by hanumesh** [lynckia/licode#163]
When i access this url  :  http://chotis2.dit.upm.es/room?id=52949225f4094e6e6c00001b.  I get the following error , 'overflowchanged' event is deprecated and may be removed. Please do not use it.

```
            I do not know the exact cause
```

**Comment by foolip** [comment]
Note that it's gone completely from Chrome 43. It looks like you were using it here:
https://github.com/ging/licode/blob/ad9d53587cf9e1d187e2bed6e066f4b89ebb62cd/erizo_controller/erizoClient/src/utils/L.Resizer.js#L245

I'd be very interested to learn what the user-facing impact of this was. Is there now some UI that fails to work entirely, or is entirely the wrong size?
