### ISSUE TITLE
Is Erizo really a MCU, not a Router/Relay?

### ISSUE THREAD

**Issue by Niklas-Peter** [lynckia/licode#170]
As far as I can see Erizo supports so far neither mixing nor transcoding, but receiving one stream and publishing it to many receivers. That is what usually is called "Router/Relay" or?

Actually this naming is not such important, but it confuses me. I tried to find anywhere transcoding/mixing options and then I noticed, that there obviously is none. However there are source files in C++ (https://github.com/ging/licode/tree/de028ed66ce24995d8e98b57039cb8967d92dfb6/erizo/src/erizo/media). Have you just not updated the documentation / not created the client API so far, so that it will be a future feature?

**Comment by nikhilrayaprolu** [comment]
so when is transcoding and mixing gonna join the licode and make it more scalable
