### ISSUE TITLE
./scripts/installErizo.sh Fails while trying to lint 

### ISSUE THREAD

**Issue by jrsarath** [lynckia/licode#1702]
OS : WSL2 Ubuntu 20.04
every other steps worked just fine
but when i tried to run ./scripts/installErizo.sh
it fails everytime when it starts to lint using cpplint

**Comment by chesky18** [comment]
This is not an issue on master codeline.

**Comment by jrsarath** [comment]
moved to mediasoup instead of licode, didnt fit my requirements
