### ISSUE TITLE
How do I configure or implement using the libnice(libniceconnection) library + ice-full?

### ISSUE THREAD

**Issue by xujingzhou** [lynckia/licode#1874]
Hi, 
   How do I configure or implement using the libnice(libniceconnection) library + ice-full? Do not want to use ice-lite + libnice or ice-full + libnicer.
 
Thanks

**Comment by lodoyun** [comment]
The default behavior is with ice-full
If you want to use libnice just use:
`
//Use of internal nICEr library instead of libNice.
config.erizo.useNicer = false;  // default value: false
config.erizo.iceLite = false; // use Ice Lite default false
`
