### ISSUE TITLE
Build Error...

### ISSUE THREAD

**Issue by prospdragon** [lynckia/licode#215]
I downloaded new version of licode and install on Ubuntu 14.04.1 LTS.

./licode/scripts/installUbuntuDeps.sh

... ... ...
libav-9.13/tests/videogen.c
libav-9.13/tools/
libav-9.13/tools/aviocat.c
libav-9.13/tools/cws2fws.c
libav-9.13/tools/graph2dot.c
libav-9.13/tools/ismindex.c
libav-9.13/tools/patcheck
libav-9.13/tools/pktdumper.c
libav-9.13/tools/probetest.c
libav-9.13/tools/qt-faststart.c
libav-9.13/tools/trasher.c
libav-9.13/version.sh
Unable to create and execute files in /tmp.  Set the TMPDIR environment
variable to another directory and make sure that it is not mounted noexec.
Sanity test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
libav-user@libav.org mailing list or IRC #libav on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solving the problem.
Makefile:1: config.mak: No such file or directory
Makefile:89: /common.mak: No such file or directory
Makefile:127: /libavutil/Makefile: No such file or directory
Makefile:127: /library.mak: No such file or directory
Makefile:201: /doc/Makefile: No such file or directory
Makefile:202: /tests/Makefile: No such file or directory
make: **\* No rule to make target `/tests/Makefile'.  Stop.
Makefile:1: config.mak: No such file or directory
Makefile:89: /common.mak: No such file or directory
Makefile:127: /libavutil/Makefile: No such file or directory
Makefile:127: /library.mak: No such file or directory
Makefile:201: /doc/Makefile: No such file or directory
Makefile:202: /tests/Makefile: No such file or directory
make: *** No rule to make target`/tests/Makefile'.  Stop.

And I continued;
./licode/scripts/installErizo.sh
Installing erizo...
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26")
-- checking for module 'glib-2.0'
--   found glib-2.0, version 2.40.2
-- Found glib-2.0: /usr/include/glib-2.0, /usr/lib/x86_64-linux-gnu/libglib-2.0.so;/usr/lib/x86_64-linux-gnu/libgobject-2.0.so;/usr/lib/x86_64-linux-gnu/libgthread-2.0.so
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   thread
--   regex
--   system
CMake Error at erizo/CMakeLists.txt:6 (message):
  lib not found: AVUTIL-NOTFOUND check README
Call Stack (most recent call first):
  erizo/CMakeLists.txt:56 (test_lib)

-- Configuring incomplete, errors occurred!
See also "/opt/licode/erizo/build/CMakeFiles/CMakeOutput.log".
Done
make: **\* No targets specified and no makefile found.  Stop.
Installing erizoAPI...
building with node-gyp
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.33 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/licode/erizoAPI/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/0.10.33/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/0.10.33',
gyp info spawn args   '-Dmodule_root_dir=/opt/licode/erizoAPI',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/opt/licode/erizoAPI/build'
  CXX(target) Release/obj.target/addon/addon.o
In file included from /opt/licode/erizo/src/erizo/media/MediaProcessor.h:12:0,
                 from /opt/licode/erizo/src/erizo/media/ExternalOutput.h:7,
                 from /opt/licode/erizo/src/erizo/OneToManyProcessor.h:12,
                 from ../OneToManyProcessor.h:5,
                 from ../WebRtcConnection.h:7,
                 from ../addon.cc:5:
/opt/licode/erizo/src/erizo/media/codecs/VideoCodec.h:16:30: fatal error: libavutil/avutil.h: No such file or directory
 #include <libavutil/avutil.h>
                              ^
compilation terminated.
make: *** [Release/obj.target/addon/addon.o] Error 1
make: Leaving directory`/opt/licode/erizoAPI/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /opt/licode/erizoAPI
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
Installing erizoController...
[erizo_controller] Installing node_modules for erizo_controller
|

> ws@0.4.32 install /opt/licode/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/opt/licode/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory`/opt/licode/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
node-getopt@0.2.3 ../node_modules/node-getopt

log4js@0.6.21 ../node_modules/log4js
├── async@0.2.10
├── semver@1.1.4
└── readable-stream@1.0.33 (inherits@2.0.1, isarray@0.0.1, string_decoder@0.10.31, core-util-is@1.0.1)

amqp@0.2.0 ../node_modules/amqp
└── lodash@1.3.1

socket.io@0.9.16 ../node_modules/socket.io
├── redis@0.7.3
├── base64id@0.1.0
├── policyfile@0.0.4
└── socket.io-client@0.9.16 (xmlhttprequest@1.4.2, uglify-js@1.2.5, active-x-obfuscator@0.0.1, ws@0.4.32)
[erizo_controller] Done, node_modules installed
[erizo_controller] Done, erizo.js compiled

**Comment by wfsovereign** [comment]
@prospdragon please tell me what is TMPDIR and how to change it? thks
