### ISSUE TITLE
Pretty clear bug in trickle-ice branch

### ISSUE THREAD

**Issue by jnoring** [lynckia/licode#224]
I'm not sure of the severity as I don't use this codepath, but in erizoAgent.js, this is pretty clearly wrong:

``` javascript
exports.addNewErizoController = function (msg, callback) {
    "use strict";

    if (msg.cloudProvider === '') {
        addNewPrivateErizoController(msg.ip, msg.hostname, msg.port, msg.ssl, callback);
    } else if (msg.cloudProvider === 'amazon') {
        addNewAmazonErizoController(msg.ip, msg.hostname, msg.port, msg.ssl, callback);
    }

};

var addNewAmazonErizoController = function(privateIP, callback) {
```

The parameters passed into addNewAmazonErizoController do not match the function declaration.  I don't use the amazon cloud provider so I do not have a fix for this.

**Comment by ArtisanCodesmith** [comment]
I see this still hasn't been merged and I've made a pull request that fixes this and also adds a WebRTC stack for iOS cordova hybrid apps here #394
