### ISSUE TITLE
Supports IE 9-11 with webrtc-everywhere plugin 

### ISSUE THREAD

**Issue by isatimur** [lynckia/licode#399]
Hi,
I've been trying to run a room on IE 11 with webrtc-everywhere plugin, but cannot get in your code where should I change the code below like said in tutorial: 
<b>Change the code you're using to attach a stream to a <audio/> or <video /> HTML5 element: 

from:  document.getElementById("eltId").src = mediaStream;  
to:  attachMediaStream(document.getElementById("eltId"), mediaStream); </b>

Do you have a plan to include IE and Safari clients for licode or do you plan to have an own plugin?
Is there a case that soon Edge browser also will be supported?

**Comment by mccob** [comment]
maybe that : see stream-subscribed event in 
https://github.com/ging/licode/blob/master/extras/basic_example/public/script.js

**Comment by mccob** [comment]
and other issue is lack of H264 support by edge : https://webrtchacks.com/chrome-firefox-edge-adapterjs/

**Comment by isatimur** [comment]
@mccob thx for considering the question!
there is an issue in JS with videoplayer.play. I will put stack trace below.
