### ISSUE TITLE
Add support to Bowser

### ISSUE THREAD

**Issue by jcague** [lynckia/licode#4]
Users should be able to connect to Lynckia from Bowser app, in both Android and iOS platforms.

**Comment by ArtisanCodesmith** [comment]
@strabbit *"iOS support is important for some, and there seem to be no other means of getting WebRTC to work on iOS."* 

**There is now!**

My pull request #394 makes Licode compatible with Cordova and it's iosrtc plugin and it works like a charm - performance is great as I not have an iOS hybrid Licode application!

If you need any help let me know! :)
