### ISSUE TITLE
BasicExample not working

### ISSUE THREAD

**Issue by frafra** [lynckia/licode#44]
I've installed licode with success, but when I try to use BasicExample I could only see my local stream.
I looked at the code and it seems that it shouldn't work like this. When localStream is initialized, it should connect to the room; this action raises room-connected event, that it should publish my local stream and subscribe to other streams; when a stream is subscribed it should create a new div containing the video, but it doesn't appear.
I noticed something strange: /getUsers/:room is always empty (obiously I used room id I've taken from /getRooms/).

Video Conference Example it seems not working (http://lynckia.com/licode/client-api.html#examples). I tried to create a new HTML file containing this code in my BasicExample, I get a video/audio sharing request, I accept it, then nothing happens, but I can see this error in my Firefox console: `SyntaxError: JSON.parse: unexpected character erizo.js:137`

**Comment by zevarito** [comment]
@lodoyun It is not working for me either, will you make those work again?
I would like to use same server for https://github.com/zevarito/ErizoClientIOS examples, wii be that possible? Thanks!

**Comment by lodoyun** [comment]
@zevarito What's not working? Most of the information in this thread issue is obsolete

**Comment by zevarito** [comment]
@lodoyun really, It wasn't working two days ago, not just for me :)

Cool, now seems working fine.

**Comment by stnwk** [comment]
Got a "Error when publishing the stream: ErizoJS is not reachable. erizo.js:174" when starting up the basic_example - any ideas?

**Comment by aholic** [comment]
@stnwk I'm face the same problem, did you solved it?
