### ISSUE TITLE
Publishing audio on Firefox fails after recent changes

### ISSUE THREAD

**Issue by mkhahani** [lynckia/licode#604]
Testing on the latest code (for 2 days ago), Firefox is stuck at **"Gathered all candidates. Sending END candidate"** and does not go further when publishing audio, no problem with video. Checked the SDP and everything seems fine. I could not go further but I'm almost sure this is about the server code.

Can any body confirm this?

**Comment by nguyendatdh93** [comment]
Yes. I have the same problem. How to solve it?

**Comment by mkhahani** [comment]
Still doesn't work.
Team, this is serious and users are complaining about it. Are you going to drop the support for Firefox?!!
