### ISSUE TITLE
add Unified Plan  multi stream   support

### ISSUE THREAD

**Issue by notedit** [lynckia/licode#695]
firefox has supported Unified Plan,  

chrome webrtc is  just doing so.

https://bugs.chromium.org/p/chromium/issues/detail?id=465349

**Comment by jcague** [comment]
This is an ongoing project right now: https://github.com/ging/licode/pull/605

PRs like https://github.com/ging/licode/pull/705 from @kekkokk and others we've been doing will help on that direction.

**Comment by notedit** [comment]
@jcague   any progress on this?

**Comment by jcague** [comment]
no progress yet, we deprioritized it due to simulcast and other things. We might restart it later this year, but I don't know specific dates, sorry.

**Comment by zombiecong** [comment]
Chrome M68 supports [Unified Plan](https://groups.google.com/forum/#!topic/discuss-webrtc/nDdDqIBtFBM)  now .May it be supported in v5 ?

**Comment by kekkokk** [comment]
It should work in the current master, am I worng @jcague ?

**Comment by notedit** [comment]
yes,  Licode support Unified Plan now.
