### ISSUE TITLE
Docker Run Error 

### ISSUE THREAD

**Issue by ForGuru** [lynckia/licode#699]
I am facing following error while running the Docker 

docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"./initDockerLicode.sh\\\": stat ./initDockerLicode.sh: no such file or directory\"\n".

<img width="1411" alt="screen shot 2017-01-17 at 10 51 14 am" src="https://cloud.githubusercontent.com/assets/14887664/22009166/04398192-dca3-11e6-872b-dd8e71bd77ee.png">

**Comment by jcague** [comment]
we've not been maintaining docker in the latest months so it will probably have issues. It's not the priority right now, but it will probably be in the medium term. And we will always accept contributions to fix it ;) .
