### ISSUE TITLE
installErizo.sh error on Ubuntu 12.04.5 x64

### ISSUE THREAD

**Issue by ForGuru** [lynckia/licode#700]
root@democonf:~# ./licode/scripts/installErizo.sh
Installing erizo...
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Found glib-2.0: /usr/include/glib-2.0, /usr/lib/x86_64-linux-gnu/libglib-2.0.so;/usr/lib/x86_64-linux-gnu/libgobject-2.0.so;/usr/lib/x86_64-linux-gnu/libgthread-2.0.so
-- Boost version: 1.46.1
-- Found the following Boost libraries:
--   thread
--   regex
--   system
CMake Error at erizo/CMakeLists.txt:6 (message):
  lib not found: NICE-NOTFOUND check README
Call Stack (most recent call first):
  erizo/CMakeLists.txt:50 (test_lib)

-- Configuring incomplete, errors occurred!
See also "/root/licode/erizo/build/CMakeFiles/CMakeOutput.log".

**Comment by johnbenzee** [comment]
Install Doxygen package separately on ubuntu,, you can google about it.

**Comment by jcague** [comment]
We only support Ubuntu 14.04. If you're having issues with other OS you can ask in discourse.lynckia.com, sorry about that
