### ISSUE TITLE
Video streaming issue on Chromium

### ISSUE THREAD

**Issue by mkhahani** [lynckia/licode#714]
The video stream from Chromium 57 is not played on any browser including Chromium itself but it works in reverse, say video from Google Chrome or Firefox is played on Chromium. Any body can confirm this?

**Comment by thehunmonkgroup** [comment]
yes, i can confirm this issue, happening with two of my Licode installations.

User A Chrome 55, User B Chrome 57, user B successfully sees subscription to user A, however user A can't see subscription to user B.

another user reported something similar here: http://discourse.lynckia.com/t/canary-57-vp8-payload-chrome-55-payload/338

**Comment by kekkokk** [comment]
able to reproduce your issue on Version 57.0.2987.13 (Official Build) dev (64-bit)

![screen shot 2017-01-31 at 10 39 32](https://cloud.githubusercontent.com/assets/15072723/22459615/a760728c-e7a1-11e6-9dd2-7655ad745afd.png)

everything works just fine on p2p.
need to give a priority cause 57 is coming. seems that on 58 everything's ok

**Comment by jcague** [comment]
I can't reproduce this issue between Version 57.0.2987.13 dev (64-bit)and Version 55.0.2883.95 (64-bit), in any of the possible combinations. I also tried with Chrome 56 with the same results.

I tried it in different environments, but all of them are up-to-date.

Could any of you guys update the code to the latest in master and give us more info about your config files if it still happens?

**Comment by kekkokk** [comment]
sure, I'll fire up the vanilla server and let you know

**Comment by thehunmonkgroup** [comment]
@jcague i'm running Licode master from Tue Sep 6 15:58:24 2016 +0200 (commit 7bc2291eb20eab8be2df9e91af91cba1abc81d7a)

there are a lot of breaking changes and things to review in the latest code compared to the code from sept. -- do you have some idea what might have changed between then and now that's causing this break? i would *much* rather patch the issue directly than deal with a major upgrade at this point...

**Comment by jcague** [comment]
Sorry, our bad, it's being a really productive time for us to change several aspects of Licode: Refactoring of code (Erizo changed a lot, for instance), updates of old libraries (libnice, gcc, etc.), new functionalities (drop packets when muting audio, bwe, ...) and APIs (new options in ErizoClient to enable and disable core functionality), improved flexibility with new configuration files (rtp media options), etc, etc. In other words, the code was getting old and difficult to maintain and to improve with new things. We're also polishing technical debt very often.

we need to start publishing release notes with all these changes, so we'll take into account your concern for future releases.

**Comment by mkhahani** [comment]
So we have less than two months to upgrade our production to the master branch. Hope to get stable till that time.

**Comment by kekkokk** [comment]
I think it's quite stable right now, I have upgraded all my servers to the current master branch. I'll let you know in a few days if everything's fine.
I can't reproduce your issue @mkhahani, probably you lost something in some merge.

I also suggest to the Licode team to evaluate the possibility to make a TAG with a new version, due to massive changes of the few months and the quite stable situation that we have achieved.

**Comment by steven8274** [comment]
It's mostly caused by RTP packet 'payload' type is not consistent with publish side and subscribe side!For example, on publish side the client and licode take 100 for VP8 packet, on subscribe side they take 96 for VP8 packet, when licode transfer packet from publish side to subscribe side it should change 100 to 96 on RTP header!

**Comment by mkhahani** [comment]
@steven8274 Thanks for the explanation but this has been fixed now so I close the issue.

**Comment by HemanthAnakapalle** [comment]
It is not clear for me, Can you guys please elaborate on how to fix this issue?
