### ISSUE TITLE
How to enable Opus?

### ISSUE THREAD

**Issue by Vidmeet1** [lynckia/licode#734]
Hi,
in earlier releases one could enable Opus by modifying SDPInfo.cpp.
Now this seems not to be possible any more? How do I enable Opus when the MCU is used? Currently it switches to PCMU in MCU mode. In P2P Opus is there.

How do I fix it?

**Comment by kekkokk** [comment]
Hi, check your rtp_media_config.js in the root or the project.

**Comment by jcague** [comment]
please use the forum to ask questions: discourse.lynckia.com
