### ISSUE TITLE
Trying to install Licode on CentOS 7

### ISSUE THREAD

**Issue by kalero** [lynckia/licode#736]
Hi,

I know you don't offer support for CentOS, but I would like to install it on that distro and share the scripts with you once it works, so if anyone could help, it will be very much appreciated.

I've translated and launched installUbuntuDeps.sh to make it work on CentOS and to install all the dependencies. Then, I've launched installErizo.sh but I get this error:

```
[root@dev licode]# ./scripts/installErizo.sh
Installing erizo...
-- Found glib-2.0: /usr/include/glib-2.0, /usr/lib64/libglib-2.0.so;/usr/lib64/libgobject-2.0.so;/usr/lib64/libgthread-2.0.so
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   thread
--   regex
--   system
-- Found glib-2.0: /usr/include/glib-2.0, /usr/lib64/libglib-2.0.so;/usr/lib64/libgobject-2.0.so;/usr/lib64/libgthread-2.0.so
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   thread
--   regex
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/licode/erizo/build
Done
[  6%] Built target gtest
[ 58%] Built target webrtc
[ 88%] Built target erizo
Linking CXX executable tests
../erizo/liberizo.so: referencia a `log4cxx::Logger::forcedLog(log4cxx::helpers::ObjectPtrT<log4cxx::Level> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, log4cxx::spi::LocationInfo const&) const' sin definir
../erizo/liberizo.so: referencia a `log4cxx::helpers::MessageBuffer::str[abi:cxx11](log4cxx::helpers::CharMessageBuffer&)' sin definir
collect2: error: ld devolvió el estado de salida 1
make[2]: *** [test/tests] Error 1
make[1]: *** [test/CMakeFiles/tests.dir/all] Error 2
make: *** [all] Error 2
```

Cause I'm not very familiar with C/C++ code, I would like to share this issue with you so maybe someone could help. Many thanks.

Kalero

**Comment by jcague** [comment]
CentOS is not supported yet, but people might help you in discourse.lynckia.com

**Comment by steven8274** [comment]
I tried install log4cxx on redhat linux, but the same error is reported!I also edited /etc/ld.so.conf to add log4cxx lib directory to it and run 'ldconfig' before make!

**Comment by steven8274** [comment]
You can manully add log4cxx lib directory to 'test/CMakeFiles/tests.dir/link.txt' by '-L/usr/local/log4cxx/lib' for example, and run 'make' again!I fix it by this way.
