### ISSUE TITLE
Support Microsoft Edge

### ISSUE THREAD

**Issue by mccob** [lynckia/licode#742]
Microsoft Edge support is here (without DataChannel but adapter.js can do that).

https://blogs.windows.com/msedgedev/2017/01/31/introducing-webrtc-microsoft-edge/

I have tried with adapter.js (webrtc adapter) and without.

I have tried with Chrome stack, bowser stack (seems to be the better for Edge actually) and Firefox Stack.

Seems to partially work : 
- Succesfully subscribed
- but no video stream (black video with loading animation)

Seems there is no Javascript error (after few corrections of chrome stack : use Media Constraints as Firefox Stack).

Only error message server side : 

SSL/DTLS error messages server side : 

       [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,082  - DEBUG     [0x7eff12bfd700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_160005530589416350, type: subscriber,  message: Received DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,082  - WARN     [0x7eff12bfd700] dtls.SSL - error in unknown state
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,082  - DEBUG     [0x7eff12bfd700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_160005530589416350, type: subscriber,  message: Sending DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,091  - DEBUG     [0x7eff257fb700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_173053864176199840, type: subscriber,  message: Received DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,091  - WARN     [0x7eff257fb700] dtls.SSL - error in unknown state
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,091  - DEBUG     [0x7eff257fb700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_173053864176199840, type: subscriber,  message: Sending DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,147  - DEBUG     [0x7eff257fb700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_173053864176199840, type: subscriber,  message: Received DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,147  - WARN     [0x7eff257fb700] dtls.SSL - error in DTLS1 read hello verify request A
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,147  - DEBUG     [0x7eff257fb700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_173053864176199840, type: subscriber,  message: Received DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,148  - WARN     [0x7eff257fb700] dtls.SSL - error in unknown state
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,148  - DEBUG     [0x7eff257fb700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_173053864176199840, type: subscriber,  message: Received DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,148  - WARN     [0x7eff257fb700] dtls.SSL - error in unknown state
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,148  - DEBUG     [0x7eff257fb700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_173053864176199840, type: subscriber,  message: Received DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,148  - WARN     [0x7eff257fb700] dtls.SSL - error in unknown state
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,148  - DEBUG     [0x7eff257fb700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_173053864176199840, type: subscriber,  message: Received DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,151  - WARN     [0x7eff257fb700] dtls.SSL - error in unknown state
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,151  - DEBUG     [0x7eff257fb700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_173053864176199840, type: subscriber,  message: Sending DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,171  - DEBUG     [0x7eff12bfd700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_160005530589416350, type: subscriber,  message: Received DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,171  - WARN     [0x7eff12bfd700] dtls.SSL - error in DTLS1 read hello verify request A
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,171  - DEBUG     [0x7eff12bfd700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_160005530589416350, type: subscriber,  message: Received DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,172  - WARN     [0x7eff12bfd700] dtls.SSL - error in unknown state
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,172  - DEBUG     [0x7eff12bfd700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_160005530589416350, type: subscriber,  message: Received DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,172  - WARN     [0x7eff12bfd700] dtls.SSL - error in unknown state
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,172  - DEBUG     [0x7eff12bfd700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_160005530589416350, type: subscriber,  message: Received DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,172  - WARN     [0x7eff12bfd700] dtls.SSL - error in unknown state
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,172  - DEBUG     [0x7eff12bfd700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_160005530589416350, type: subscriber,  message: Received DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,176  - WARN     [0x7eff12bfd700] dtls.SSL - error in unknown state
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,176  - DEBUG     [0x7eff12bfd700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_160005530589416350, type: subscriber,  message: Sending DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,200  - DEBUG     [0x7eff12bfd700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_160005530589416350, type: subscriber,  message: Received DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,200  - WARN     [0x7eff12bfd700] dtls.SSL - error in unknown state
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,201  - DEBUG     [0x7eff12bfd700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_160005530589416350, type: subscriber,  message: Received DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,201  - DEBUG     [0x7eff12bfd700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_160005530589416350, type: subscriber,  message:HandShakeCompleted, transportName:video, readyRtp:1, readyRtcp:1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,201  - DEBUG     [0x7eff12bfd700] WebRtcConnection - id: YU0Af5b6tzQVVw8LrxYL_160005530589416350, type: subscriber,  transportName: video, new_state: 3
    2017-02-08 16:21:48,201  - INFO     [0x7eff12bfd700] WebRtcConnection - id: YU0Af5b6tzQVVw8LrxYL_160005530589416350, type: subscriber,  newGlobalState: 104
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48.201  - INFO: ErizoJSController - message: WebRtcConnection status update, id: YU0Af5b6tzQVVw8LrxYL_160005530589416350, status: 104, type: subscriber
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,202  - DEBUG     [0x7eff257fb700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_173053864176199840, type: subscriber,  message: Received DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,202  - WARN     [0x7eff257fb700] dtls.SSL - error in unknown state
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,202  - DEBUG     [0x7eff257fb700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_173053864176199840, type: subscriber,  message: Received DTLS message, transportName: video, componentId: 1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,202  - DEBUG     [0x7eff257fb700] DtlsTransport - id: YU0Af5b6tzQVVw8LrxYL_173053864176199840, type: subscriber,  message:HandShakeCompleted, transportName:video, readyRtp:1, readyRtcp:1
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,202  - DEBUG     [0x7eff257fb700] WebRtcConnection - id: YU0Af5b6tzQVVw8LrxYL_173053864176199840, type: subscriber,  transportName: video, new_state: 3
    2017-02-08 16:21:48,202  - INFO     [0x7eff257fb700] WebRtcConnection - id: YU0Af5b6tzQVVw8LrxYL_173053864176199840, type: subscriber,  newGlobalState: 104
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48.202  - INFO: ErizoJSController - message: WebRtcConnection status update, id: YU0Af5b6tzQVVw8LrxYL_173053864176199840, status: 104, type: subscriber
    2017-02-08 16:21:48.203  - INFO: ErizoController - message: addSubscriber, state: SUBSCRIBER_READY, streamId: 160005530589416350, clientId: YU0Af5b6tzQVVw8LrxYL
    2017-02-08 16:21:48.205  - INFO: ErizoController - message: addSubscriber, state: SUBSCRIBER_READY, streamId: 173053864176199840, clientId: YU0Af5b6tzQVVw8LrxYL
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,326  - DEBUG     [0x7eff12bfd700] WebRtcConnection - id: 160005530589416350, type: publisher,  unknownSSRC: 2177499151, localVideoSSRC: 86575230, localAudioSSRC: 0
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,361  - DEBUG     [0x7eff257fb700] WebRtcConnection - id: 173053864176199840, type: publisher,  unknownSSRC: 2177499151, localVideoSSRC: 3476074881, localAudioSSRC: 0
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:21:48,396  - DEBUG     [0x7eff12bfd700] WebRtcConnection - id: 160005530589416350, type: publisher,  unknownSSRC: 2177499151, localVideoSSRC: 86575230, localAudioSSRC: 0
    [erizo-885e6f6b-bc2f-1f33-c572-9eed45b9c7aa] 2017-02-08 16:18:47,652  - DEBUG [0x7eff257fb700] WebRtcConnection - id: 173053864176199840, type: publisher,  unknownSSRC: 2177499151, localVideoSSRC: 3476074881, localAudioSSRC: 0

Help appreciated :)

**Comment by letchoo** [comment]
Would be great if Edge could be supported by licode as well

**Comment by mccob** [comment]
OK, tried again. It's working like a charm. Can be closed.

:)

**Comment by aalonsog** [comment]
So... do you confirm we are compatible with this Edge version? Which stack have you finally used?

**Comment by kekkokk** [comment]
yeah, would be nice to have some details / PR :)

**Comment by mccob** [comment]
using bowser stack.

else if (window.navigator.userAgent.match('Edge') !== null) {
        // Firefox
        browser = 'bowser';
    }

**Comment by mccob** [comment]
and you have to use adapter.js 

	<script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>

**Comment by mccob** [comment]
PR : https://github.com/lynckia/licode/pull/743

**Comment by aalonsog** [comment]
Thanks! Let's continue the discussion there

**Comment by mkhahani** [comment]
> @aalonsog On the other hand, perhaps this is a good moment to discuss if we want to migrate our Browser stacks to the adapter...

Some parts of Licode are really old and out dated. One of them is Browser stacks which can be replaced by adapter.js. Another one is Socket IO. I hope some day we have them upgraded.
