### ISSUE TITLE
Documentation for setting up Licode in a docker container

### ISSUE THREAD

**Issue by eliperelman** [lynckia/licode#75]
For ease of distribution, I think it would be great if you could outline necessary dependencies and instructions for installing Licode in the base Ubuntu image for docker. Maybe there could also be an official Licode image up on http://images.docker.io. This would save users from having to go through the installation process and let them focus on writing their implementations.

**Comment by m59peacemaker** [comment]
@zoltan-fedor  I can't get licode installed properly on any base image for docker... Could I see the Dockerfile you used?

**Comment by zoltan-fedor** [comment]
@m59peacemaker , sorry, I didn't use a Dockerfile, but installed it manually in docker and as you can imagine it was too long ago to remember the steps... :-(
