### ISSUE TITLE
how to install licode on ubuntu 16.04 LTS.

### ISSUE THREAD

**Issue by johnbenzee** [lynckia/licode#757]

**Comment by johnbenzee** [comment]
I followed the installtion instruction from http://lynckia.com/licode/install.html, the installtion goes smooth till step 4, in the step 4 when I run the cammand ./licode/scripts/installErizo.sh,  I get the following error.
Installing erizo...
CMake Error at third_party/webrtc/src/CMakeLists.txt:6 (message):
  lib not found: LOG-NOTFOUND check README
Call Stack (most recent call first):
  third_party/webrtc/src/CMakeLists.txt:34 (test_lib)


-- Configuring incomplete, errors occurred!
See also "/home/webuser/licode/erizo/build/CMakeFiles/CMakeOutput.log".
any help would be much appreciated.

**Comment by jcague** [comment]
We haven't tried Ubuntu 16.04 yet. Please use discourse.lynckia.com to make questions there please. This channel is only for issues.
