### ISSUE TITLE
Licode is an SFU/MCU ???

### ISSUE THREAD

**Issue by hailuavitinh** [lynckia/licode#796]
I have read your previous comments, and you have said Licode is SFU / MCU. But I'm wondering when it can run under the SFU model and when it runs the MCU model?

Can you explain this to me? I'm really confused about this.

Thanks,

**Comment by aalonsog** [comment]
Hi @hailuavitinh, please use [the forum](http://discourse.lynckia.com/) to ask this kind of questions. This channel is only for issue reporting.

By default, Licode acts as SFU, getting the streams from publishers and forwarding them to the subscribers. But it also supports MCU functionalities such us recording, external output streaming, etc.

**Comment by hailuavitinh** [comment]
First, thank you for your feedback.

I had posted this topic on Discourse, but my account was blocked temporary, so I can not create topic or comment.

And my question is: Model MCU functionalities recording, external output streaming, etc.. So if video call has 5 users that 4 users run Model SFU, can the last user receive stream from others through model MCU (just 1 stream)? If yes, can you guide me how to do it?

**Comment by lodoyun** [comment]
I've approved your post back in discourse. We can continue the discussion there.

**Comment by hailuavitinh** [comment]
I have moved this comment to discourse. Hope to receive your response

Thanks.
