### ISSUE TITLE
Local OSX build suddenly stop collect any candidates on Chrome

### ISSUE THREAD

**Issue by zevarito** [lynckia/licode#799]
Hello,

I understand this is a kind of weird issue to report but I am facing it and perhaps it is a bug or someone can help pointing me out what is happening.

I was playing with RTSP locally on a OSX machine and everything went fine it worked both for Chrome and Firefox, after a while it suddenly stop working on Chrome while in Firefox everything behaves as expected.

What I noticed is that Chrome doesn't gather any candidates, I don't know if Chrome did update himself silently and break something but the version I have right now is: 57.0.2987.98 (64-bit).

**Comment by mkhahani** [comment]
Hi,

Check this out: https://github.com/lynckia/licode/issues/714

**Comment by zevarito** [comment]
@mkhahani thanks, I follow up there.

**Comment by zevarito** [comment]
I've reopened this cause doesn't seem to be the exact same issue as #714 while it might be related to M57 as-well. I've tested with latest master and a couple of modified Client and Erizo and it is the same.
