### ISSUE TITLE
Run ErizoController via HTTPS

### ISSUE THREAD

**Issue by ivopavlik** [lynckia/licode#81]
It is not so simple to secure ErizoController. Port is hardcoded and client's getting server URL is not transparent. Client gets IP address.
When I use Licode via HTTPS, mixed content is reported. Since Firefox doesn't support mixed content by default, page is not correctly loaded by Firefox. Chrome reports "only" warnings.
This is quite important issue, because screen sharing is available only via HTTPS.

**Comment by cracker0dks** [comment]
thank you! you saved me :+1:

**Comment by panaali** [comment]
@cracker0dks Yw, I wanted to place a pull request fot this, bus as you see nobody cares.

**Comment by julesbloemen** [comment]
Thanks @panaali !!
