### ISSUE TITLE
Mongodb failed on saving data

### ISSUE THREAD

**Issue by mntan** [lynckia/licode#833]
Hi, 
Has anyone got this problem with mongoDB? As I know the licode's code, we are using the **mongojs** to interact with mongoDB.
I've setup a licode at an ec2 (c3.2xlarge, 32 GB SSD).
```
System load:  0.05               
Processes:           160
Usage of /:   29.2% of 31.36GB   
Memory usage: 6%                 
Swap usage:   0%
```
The setup was successfully, the video conference, the screenshare was working properly but I was gotting a problem with mongoDB recently time. 
I've tested with concurrent requests to ask creating a **roomID** for using in video conference feature.
I am attaching the result of my testing as following.

The code for creating a room as following below:
```
rooms.create(req.body.name, data, p2p, {id: service.id, key: service.key}, function(room) {
        res.send(room._id);
    }, function() {
        res.send('error');
    });
```

I've using the for loop statement to make a script in order to post the concurrent requests to that created room endpoint.
There are some results about (the request has been successfully with **roomID** has been saved into mongoDB / the total requests) as bellow:
P/s: mongoDB on **services** collections with **rooms** field is having 1590 elements.
```

  8  /8
10  /10
19  /20
41  /50
73  /100
12  /16
15  /20
  7  /10
  5  /8
  2  /5

```
Could I get an advise for improving this mongodb problem on saving data?

**Comment by aalonsog** [comment]
Hi @mntan, please, use Nuve API to create Licode resources in Nuve (rooms, services, etc). This ensures every related stuff is created and configured correctly. 

[Here](http://licode.readthedocs.io/en/master/server_api/) you can find the API details.

BR
