### ISSUE TITLE
For some reason screen share (stream with video) doesn’t works on chrome 57 version.

### ISSUE THREAD

**Issue by HemanthAnakapalle** [lynckia/licode#843]
On chrome 57 version:

1) I can notice ... chrome extension is proving the screen video properly.
2) I played on local side just before publishing ... it is fine.
3) I recorded the screen share stream .... it is fine at licode side.

But what i notice is .... content is not coming from licode during subscription.

NOTE: All events are proper, problem is with the stream content.
I added a "poster" for the video tag, where it is shown forever, which means there is no enough content to display the video.

Any guidance to fix this issue?

Raised on discourse too ... http://discourse.lynckia.com/t/critical-for-some-reason-screen-share-stream-with-video-doesnt-works-on-chrome-57-version/445

Thanks,
Hemanth

**Comment by menelike** [comment]
Maybe this is related to https://nimblea.pe/monkey-business/2017/01/19/webrtc-asterisk-and-chrome-57/

**Comment by jcague** [comment]
I can't reproduce it and we're using it in production with screen sharing. Please, double check that the "poster" property works as expected. Please, also check chrome://webrtc-internals to see if you're receiving content/bitrate or not.

**Comment by HemanthAnakapalle** [comment]
It is working, Thanks.
