### ISSUE TITLE
Mongodb3.4 error

### ISSUE THREAD

**Issue by steven8274** [lynckia/licode#844]
When I install Mongodb 3.4, if I run initBasicExample.sh, make this error:
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters

**Comment by jcague** [comment]
please install the version that comes with Ubuntu 14.04.

**Comment by steven8274** [comment]
I install licode on Redhat linux(RHEL6.3 server). If I install mongodb 2.6.12, there won't be any error.
