### ISSUE TITLE
about stream-failed

### ISSUE THREAD

**Issue by YHubY** [lynckia/licode#853]
Hi

Can you see the cause of stream-failed in client JS?
How should I deal with it when it occurs?

room.addEventListener('stream-failed', function (){
  // todo
});

**Comment by kekkokk** [comment]
you may check if the id of the stream is the id of an your "publishing" stream or not. in that case you may want to re-publish or re-subscribe to that stream.
It usually occurs during an Ice failed event or connectivity issue.
I don't think you really need the cause, just republish or resubscribe
cheers

**Comment by YHubY** [comment]
thank you!
Do not know the stream as an error?

**Comment by jcague** [comment]
please use discourse to ask question to the community, thanks!
