### ISSUE TITLE
wrong check on NiceConnection::sendData ?

### ISSUE THREAD

**Issue by zevarito** [lynckia/licode#859]
I am getting a lot of Debug message like `%s message: Sending less data than expected, sent: %d, to_send: %d`, the message is output when `(val != 1)`[0], according to Libnice docs[1] the return value should be "The number of bytes sent, or negative error code", seems that the check expect to be sent only one byte, is that correct? Blaming the file I found that previously the check was made like `(val != len)`[2] which make more sense, but still not clear since the same message will apply for greater and lesser values and no error codes (less than 0 values) are check. Please confirm what is the behavior and I am up to send a patch if needed. Thanks.

[0] https://github.com/lynckia/licode/blob/master/erizo/src/erizo/NiceConnection.cpp#L143
[1] https://nice.freedesktop.org/libnice/NiceAgent.html#nice-agent-send
[2] https://github.com/lynckia/licode/blame/036aed83b435b66d936338706cf187f02e4df059/erizo/src/erizo/NiceConnection.cpp#L132

**Comment by kekkokk** [comment]
Already opened a PR [PR#858](https://github.com/lynckia/licode/pull/858/files)

**Comment by jcague** [comment]
it's caused by an update in a libnice version, thanks for the fast report @zevarito and for the patch @kekkokk

**Comment by zevarito** [comment]
cool! closing...
