### ISSUE TITLE
can't start up the container

### ISSUE THREAD

**Issue by Robin2009** [lynckia/licode#872]
I tried to start the basic demo container by running `docker run -d --name licode -p 3001:3001 -p 8080:8080 -p 3000:3000 -p 30000-31000:30000-31000/udp -e "PUBLIC_IP=192.168.0.106" lynckia/licode` on my mac but constantly got this error:
```
Error response from daemon: driver failed programming external connectivity on endpoint licode (9a068b6414913da76a8627d05d3083816310bf556a2a704d325a5e65015c5045): Error starting userland proxy: Bind for 0.0.0.0:30408: unexpected error Hostnet.Host_uwt.Sockets.Too_many_connections
Error: failed to start containers: licode
```
I had already changed my max-connections from 900 to 1200 and closed other applications but that didn't help.  Appreciate any suggestion ...

**Comment by lodoyun** [comment]
We've just updated the image so please update it as the previous one can cause problems.
In any case, depending on the docker configuration/environment, having 1000 udp ports forwarded can be problematic, try this:
`docker run -d --name licode -p 3001:3001 -p 8080:8080 -p 3000:3000 -p 30000-30000:30050-30050/udp -e "PUBLIC_IP=192.168.0.106" lynckia/licode`

**Comment by Robin2009** [comment]
Hi @lodoyun , thanks for your suggestion and it works now!

**Comment by Robin2009** [comment]
@lodoyun ,  I got another issue when I run docker locally and use firefox to open the demo, which saying that
```
WARNING:  Publishing Stream 665544631310986500 has failed after successful ICE checks
DEBUG:  Event: stream-failed
Stream Failed, act accordingly
DEBUG:  Received a removeStream for 665544631310986500 and it has not been registered here, ignoring.
INFO:  Stream unpublished
```
But the same demo runs perfect fine in Chrome if opened two or three pages at the same time. I've searched some articles related to this issue and it looks like that the port range is the root  cause in my case ([Licode: Publishing Stream has failed after successful ICE checks](http://stackoverflow.com/questions/41074674/licode-publishing-stream-has-failed-after-successful-ice-checks)).
One more question, like you said `In any case, depending on the docker configuration/environment, having 1000 udp ports forwarded can be problematic`, is it still good to host licode inside a docker, or, the better way is to install licode separately on any physical/virtual machine? Looking forward to your suggestion about that...thank you!

**Comment by lodoyun** [comment]
I've reproduced the Firefox issue and will work on a fix. Thanks!
I would still recommend to install Licode from source for production. We're actively working on docker support and our plan is to test it in a production environment. We will iterate and hopefully make it a stable alternative but I'm afraid we're not there yet.

**Comment by Robin2009** [comment]
Thanks a lot, that's really a quick reply and I do appreciate your patience. 
I should say you guys are amazing for creating this cool stuff!  salute~
