### ISSUE TITLE
Install failure in initLicode.sh

### ISSUE THREAD

**Issue by windsurfdrew** [lynckia/licode#879]
I'm doing a clean install of the latest licode build on a mac when I see this error when running initLicode.sh:

ERROR: RPC - message: AMQP connection error killing process, errorMsg: code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 5672

At that point there is no nuve process, but erizoController and erizoAgent are running, and I am seeing the same warning messages reported in [issue #571](https://github.com/lynckia/licode/issues/571)

ERROR: ErizoController - message: addECtoCloudHandler cloudHandler does not respond - fatal

If we run initBasicExample.sh, the BasicExample nodejs process just exits. If I look inside the mongoDB, I see one service, but no rooms and no tokens.

We're seeing the error on two different macs, one using the latest source code from today, and the other from April 21st. It seems that if we re-run some combination of the install and init steps over and over, we can sometimes get beyond this error.

**Comment by kekkokk** [comment]
I sometimes happens to me. I suggest you to run initLicode, get this error frew times than do a killall node. wait 10/15 seconds and start initLicode again. it should work.

more efficient solution would be do a brew services start mongodb before initLicode to make sure mongodb is running properly

**Comment by lodoyun** [comment]
It's a rabbitmq in Mac issue, I haven't been able to reproduce it consistently. For some reason it stops accepting connections sometimes even if the process is running. 
Doing `brew services restart rabbitmq` and waiting a few seconds does the trick for me.

**Comment by windsurfdrew** [comment]
Thanks for the tips. The behavior has subsided (and the installation is working) for now, but will try those suggestions and report back when it happens again in the next couple days.

**Comment by windsurfdrew** [comment]
Indeed, it seems like rabbitmq on mac does sometimes fail, and the fix recommended by lodoyun seems to solve the problem. Thanks.

**Comment by alexvasilchenko** [comment]
Hey!

I know issue is closed... But I'm getting similar issue on OS X after fresh install: 
Unhandled connection error: INTERNAL_ERROR
ERROR: AMQPER - message: AMQP connection error killing process, code: 541

Workarounds suggested here didn't help:
brew services restart rabbitmq

Also I did kill all node processes and made sure mongo is running. Do you have any idea how to make it working?

Thanks in advance!

**Comment by alexvasilchenko** [comment]
OK, figured this out! The problem was that rabbitmq installed by homebrew didn't work properly.
I started rabbitmq-server and it shown it couldn't modify some files due to permission issues, so I did and it helped. 

sudo chown -R <my-user-name> /usr/local/var/lib/rabbitmq

After it everything worked!

**Comment by hamzajamilryk** [comment]
Hi,

I am getting the following error on ./scripts/initLicode.sh

47867
47869
Checking dir /Users/hamzajamil/licode/build/libdeps/nvm
Running nvm
Unhandled connection error: INTERNAL_ERROR
2021-09-29T17:36:13.395  - ERROR: RPC - message: AMQP connection error killing process, errorMsg: code: 541
Checking dir /Users/hamzajamil/licode/build/libdeps/nvm
Running nvm
Found '/Users/hamzajamil/licode/.nvmrc' with version <12.13.0>
Now using node v12.13.0 (npm v6.12.0)
Checking dir /Users/hamzajamil/licode/build/libdeps/nvm
Running nvm
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module './../../bw_distributor_config'
Require stack:
- /Users/hamzajamil/licode/erizo_controller/erizoController/erizoController.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/hamzajamil/licode/erizo_controller/erizoController/erizoController.js:12:29)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/hamzajamil/licode/erizo_controller/erizoController/erizoController.js'
  ]
}
