### ISSUE TITLE
ErizoJS crash in DtlsSocket::handlePacketMaybe

### ISSUE THREAD

**Issue by steven8274** [lynckia/licode#891]
**Description**
ErizoJS process crashed in DtlsSocket::handlePacketMaybe at line:

`int r = BIO_write(mInBio, bytes, len);
  assert(r == static_cast<int>(len));  // Can't happen`

**Steps to reproduce the issue:**
1.Two users publish and subscribe with each other.
2.Both users unpublish and re-publish.
3.The two users re-subscribe the newly published streams.

**Describe the results you received:**
The process crashed randomly.The probability of crash is very low.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
It happens occasionally with a very low probability.

**Licode commit/release where the issue is happening**
master branch fetched on 20170510

**Additional environment details (Local, AWS, Docker, etc.):**
I run licode on RHEL 6.3

**Comment by steven8274** [comment]
I found the problem!The error caused by 'call BIO_Write after mInBio has been released'!In detail, this error is generated as:
1.the 'DtlsSocket' has been closed.
2.Then called DtlsSocket's handlePacketMaybe to process packet.

To fix it we can add these code in 'handlePacketMaybe' function at the begin:
`
if (mSsl == NULL) {
    ELOG_WARN("handlePacketMaybe called after DtlsSocket closed: %p", this);
    return false;
  }
`

**Comment by kekkokk** [comment]
also happened to me
![screen shot 2017-05-25 at 12 01 53 pm](https://cloud.githubusercontent.com/assets/15072723/26447018/df44a78c-4146-11e7-9931-7f428c37c9d6.png)
I'll do a PR for you
