### ISSUE TITLE
Be able to seamlessly mute the video stream

### ISSUE THREAD

**Issue by menelike** [lynckia/licode#906]
When I need to deal with tough bandwidth scenarios I sometimes also need to manually mute/unmute the videostream. This is currently only possible with a re-subscription which results in a short connection break where the user is disconnected for a short period of time.

It would be great if I could mute/unmute the video as easy as muting the audio channel.

http://licode.readthedocs.io/en/master/client_api/#schemes describes that licode is already able to mute the video e.g. `audio-only mode`.

> notify-break: Licode will notify subscribers, stop adapting the publisher to problematic subscribers and relegate them to audio-only mode.

My hope is that this functionality can just be explicitly exposed to the client.

**Comment by jcague** [comment]
We don't have a mute video feature currently in the client, but we'll considering adding it in the future, thanks!
