### ISSUE TITLE
How can I achive one-to-many

### ISSUE THREAD

**Issue by leoagle** [lynckia/licode#913]
Hello 
     I am working on one-to-many audio conference by using Licode as server. Only one user can send audio data to sever in a conference room at one moment, others mute/unmute the talker's voice. When the talker done speak, someone else is able to talk. I know there are one-to-many and broadcast functions in Licode, but my scenario is anyone could be the speaker, not someone be speaker all the time. How could I change the code to make this one-to-many happen?  Could you give me some suggestions? Thanks in advance.

**Comment by jcague** [comment]
please use the forum to ask these questions.
