### ISSUE TITLE
How WebRTC transfer Data through Room

### ISSUE THREAD

**Issue by alimhabib** [lynckia/licode#934]
I know in WebRTC we transfer Data using peer to peer communication and the only Role of webRTC signaling server is only to initiate and maintain the communication between the peers and any Data (video , audio , Raw Data , Files,.....) will be transferred through the peer to peer channel

but in Room can't find an article to explain how Data will be transferred from one to n participant in this Room will it be peer to peer channels or the server will play another role , this part is a little bit confusing I installed Kurento ,MultiRTC, and Licode , ........ but I can't figure out all I noticed is each room reserve a port on the server ,if any one can help me with that

**Comment by jcague** [comment]
We transfer data using WebSockets and all messages pass through the server (even in P2P), we don't use Webrtc's data channel at all. 

It has its pros and cons, like having the opportunity to log certain messages in the server if your app require it, or it gives us the opportunity in the future to send data from the server.
