### ISSUE TITLE
All adaptation schemes never fire bandwidth-alert

### ISSUE THREAD

**Issue by marklawlor** [lynckia/licode#935]
**Description**

All adaptation schemes never fire any bandwidth-alerts. The issue is caused by the `wrtc.getStats` function always returning undefined, which causes the adaptor interval to be cleared. `wrtc.getStats()` was changed to an async function that expects a callback. None of the adaption schemes have been updated with this change.

I believe this commit was the cause https://github.com/lynckia/licode/commit/adfe2fad1c9f741cdf521a01f85b0d87e09d45c3#diff-05aff6e97256fcd508522ca8e38c1275R365

**Steps to reproduce the issue:**
1. Modify basic example so that it uses a schema `extras/basic_example/public/script.js:106` (add the config to the options object)
2. Add console log after the `wrtc.getStats` function and the `if (!newStats)` if statement to check the value of `newStats`
3. Rebuild licode (I was testing using the latest Dockerfile, using volumes to apply the two changes stated above)
4. Start the basic example with two clients.

**Describe the results you received:**

`wrtc.getStats()` always returns undefined and clears the setInterval timer

**Describe the results you expected:**

`wrtc.getStats()` expects a callback and the adaptors need to refactored to account for this change

**Comment by iamnibin** [comment]
I am also facing the same problem

**Comment by lodoyun** [comment]
Should be fixed in #973. Feel free to give it a try, see how it goes and reopen this if you are experiencing more problems
