### ISSUE TITLE
Simulcast doesn't work in Chrome >= 60

### ISSUE THREAD

**Issue by kekkokk** [lynckia/licode#938]
**Description**

Simulcast doesn't work on Chrome >= 60.

**Steps to reproduce the issue:**

1. Install vanilla Licode
2. open basicexample in whatever chrome version and publish a stream with ?simulcast=true
3. open basicexample in another computer with chrome >= 60 (from current beta) with ?onlysubscribe=true

**Describe the results you received:**

opening basicexample/quality_layers.html we can see that estimated bandwidth is 0kb

**Describe the results you expected:**

we should see the black bar of the estimated bandwidth growing.

**Additional information you deem important (e.g. issue happens only occasionally):**

seems that Licode doesn't receive any REMB. They are correctly negotiated according to sdps but no REMB is received (or maybe we don't parse them correctly? (I don't think so)). 

from SenderBandwidthEstimationHandler: 
` // TODO(pedro) Implement alternative when there are no REMBs `

**Licode commit/release where the issue is happening**

78599cd53f8e90a2314b12f40344e513f49f914d

**Additional environment details (Local, AWS, Docker, etc.):**

AWS EC2

**Comment by kekkokk** [comment]
@jcague @lodoyun Do you think it's a Chrome or a Licode bug? 
I'm starting thinking that it's a Chrome problem.
The fact is that the current beta will be released in 7 days so we might consider opening a ticket in monorail and / or  switch to another approach without the use of rembs.
At this purpose:
 - Can you suggest me some method to debug if chrome is correctly sending rembs? I tried wireshark but it cannot decode rembs or maybe I am using wrongly. (I only see RR and SR, even with chrome 59 that does work).
I also tried to enable webrtc logging in chrome but it doesn't tell me if is sending REMBS (tried with webrtc log level 5)
- Why in SenderBandwidthEstimationHandler we call UpdateReceiverBlock only if we already have received rembs? cannot the algo works only with RR? I tried to force the update once every RR comes in, even without rembs, but seems that the estimation continues growing until reach the 100M limit. It reacts to fluctuation (it degrades on packet lost ) but grows faster than it decrease.

**Comment by jcague** [comment]
I was able to reproduce, thanks @kekkokk! seems like Chrome is actually sending REMB, but we don't handle them properly somehow. We'll investigate it further next week.

![image](https://user-images.githubusercontent.com/557698/27725782-36456dda-5d78-11e7-9c06-aa04532f1c5b.png)

**Comment by jcague** [comment]
btw, I used the event log in webrtc-internals
![image](https://user-images.githubusercontent.com/557698/27726057-2a8f4c8a-5d79-11e7-9730-002a227467c5.png)

 which generates a file that can then be translated to a .pcap with Fippo's tool: https://github.com/fippo/dump-webrtc-event-log

And .pcap files can be read by Wireshark. 

It's better than using Wireshark directly in the network interface because packets are decrypted.

**Comment by kekkokk** [comment]
precious information, thanks!
