### ISSUE TITLE
Error: Cannot find module 'eslint-config-airbnb' while initiating server after webpack integration

### ISSUE THREAD

**Issue by arsenicraghav** [lynckia/licode#960]
It's throwing an error now after the webpack support got added :

/home//licode/node_modules/eslint/lib/config/config-file.js:434
throw e;
^

Error: Cannot find module 'eslint-config-airbnb'
Referenced from: /home/licode/.eslintrc
at ModuleResolver.resolve (/home/licode/node_modules/eslint/lib/util/module-resolver.js:74:19)
at resolve (/home/licode/node_modules/eslint/lib/config/config-file.js:515:25)

**Comment by lodoyun** [comment]
Update and reinstall all the dependencies, this was fixed int #957
