### ISSUE TITLE
Cannot find erizo.js file after installation

### ISSUE THREAD

**Issue by khoachung89** [lynckia/licode#966]
I have installed licode on Ubuntu 14.04 without any issue - following the guide on homepage.
Up to the last step (step 6), I cannot run the ./scripts/initBasicExample.sh script because the erizo.js file in /erizo_controller/erizoClient/dist directory missed.

I'm not sure this file is generated at which step but i guess it's result of an issue when installing erizoController.

How can I run the example now? How do I make sure erizoController is working well after installation?

**Comment by aalonsog** [comment]
Hi, erizo.js file is generated when executing installErizo.sh script. Specifically during the install_erizo_controller() task. Then, when you execute initiBasicExample.sh script, the file is copied into basic example. Check that no errors happened during the script execution.

**Comment by jcague** [comment]
this is fixed by #983
