### ISSUE TITLE
I can not create multiple rooms in Licode to add users

### ISSUE THREAD

**Issue by evilword666** [lynckia/licode#968]
I'm currently working with Licode, and I have installed my server and everything goes well with the example code. 
Now I want to create different an extra room to and then I want to add a couple of users inside of this  room. 
My question is: how can I create different rooms  and additionaly  add each pair of users. 
In the example that comes in the project folder all the users that I created go directly to the default room but I don´t need that.
If someone could orient myself with some example or give me some reference to overcome this requiement, I would appreciate it

**Comment by arsenicraghav** [comment]
Are you sure it's an issue?  or just a question on how to do it ?

**Comment by jcague** [comment]
Please read the info in: http://licode.readthedocs.io/en/stable/server_api/#rooms and http://licode.readthedocs.io/en/stable/server_api/#tokens

**Comment by evilword666** [comment]
@arsenicraghav @jcague  yes, I did not know how to create it, but I already got it, thank you very much.
