### ISSUE TITLE
Getting Unwanted background sound when we are subscribing stream from Microsoft Edge (v 15.15063).

### ISSUE THREAD

**Issue by SanthoshArya** [lynckia/licode#970]
**Description**
   Getting Unwanted background sound in CROSS BROWSER when we are subscribing stream from 
   Microsoft Edge (v 15.15063).

**Steps to reproduce the issue:**
  Create the conference and start it from chrome/firefox, let one of the attendee join conference from 
  EDGE.

**Description of the results received:**
   After stream subscribed event from EDGE we are getting unwanted background sound (like tick-tick) 
   to every one in the conference.

**Additional information:**
   We are getting this issue as consistent, Even though all streams are in mute everyone in conference 
   hearing this unwanted background sound.
   **Note:** Sound is coming from the system speaker.

**Comment by kekkokk** [comment]
@SanthoshArya 
did you manage to change something to be able to use edge or worked out of the box?
are you doing a p2p call or an erizo call?

**Comment by arsenicraghav** [comment]
@SanthoshArya 
Are you sure you want to use Microsoft Edge ? Have  a look at the Erizo.getBrowser in Connection.js Also webrtc isn't a thing for a Edge for now I guess.

**Comment by jcague** [comment]
Microsoft Edge is not officially supported yet, although we're using adapter.js now which should help adapting it. Anyway, any echo issue is usually caused by some different behaviour in the browser. You may want to use Opus (which I don't know if it's support by Edge), or similar instead, to see if it helps.

**Comment by kekkokk** [comment]
I confirm opus solves the noise caused by pcmu in edge.
edge still have some limitations. I opened a bug:

[EDGE DEV](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12919339/)
