### ISSUE TITLE
P2P Room Connection Problem

### ISSUE THREAD

**Issue by sebastianfelipe** [lynckia/licode#971]
Hi guys, I'm implementing a licode for a personal project and I already set a https server and a public IP, everything works fine using rooms that are not P2P. When I create a P2P room then I have problem, I don't know why. It says:

Uncaught TypeError: Object(...) is not a function -> erizo.js:1587

I don't know if I need to configure something else or what. That error appeared on the console log using Chrome Browser. As I say, when I use the same configurations in non-p2p rooms, there is no problem, but when I use P2P rooms then that error appears. Before that error, the DEBUG is creating an the the related event is "Event: signaling_message_peer"

I'd really appreciate you have a look at this, I think there is a bug.

Thanks,
Sebastián.

**Comment by sebastianfelipe** [comment]
I found the problem. That line, the 1587 of the compiled file, is:

stream.pc = Object(__WEBPACK_IMPORTED_MODULE_0__Connection__["a" /* default */])(getP2PConnectionOptions(stream, peerSocket));

But it should be:

stream.pc = Object(__WEBPACK_IMPORTED_MODULE_0__Connection__["a" /* default */]).buildConnection(getP2PConnectionOptions(stream, peerSocket));

After that Object, should call the buildConnection method, at least I tried using that method and I got the solution of that problem. Well, you have to modify that where it needs to be modified, I propose that solution, what do you think?

:)

**Comment by jcague** [comment]
your'e completely right, thanks for the heads up! @kekkokk already has a solution, will merge it  to master today

**Comment by sebastianfelipe** [comment]
Perfect! :)
