### ISSUE TITLE
docker   error

### ISSUE THREAD

**Issue by wuxingzhong** [lynckia/licode#978]
** error log 
```
licode_1  | No parameters -- starting everything
licode_1  | Running NVM
licode_1  | Found '/opt/licode/.nvmrc' with version <6.9.2>
licode_1  | Now using node v6.9.2 (npm v3.10.9)
licode_1  | [licode] Starting mongodb
licode_1  | about to fork child process, waiting until server is ready for connections.
licode_1  | forked process: 255
licode_1  | all output going to: /opt/licode/build/mongo.log
licode_1  | log file [/opt/licode/build/mongo.log] exists; copied to temporary file [/opt/licode/build/mongo.log.2017-07-23T16-01-47]
licode_1  | ERROR: child process failed, exited with error number 100
licode_1  | [licode] Creating superservice in localhost/nuvedb
licode_1  | MongoDB shell version: 2.4.9
licode_1  | connecting to: localhost/nuvedb
licode_1  | Sun Jul 23 16:01:52.411 Error: couldn't connect to server localhost:27017 at src/mongo/shell/mongo.js:147
licode_1  | exception: connect failed
licode_1  | exception: connect failed
licode_1  | exception: connect failed
licode_1  | Mongo Logs:
licode_1  | Sun Jul 23 16:01:47.294 [initandlisten] MongoDB starting : pid=255 port=27017 dbpath=/opt/licode/build/db 64-bit host=3d17b7f0986e
licode_1  | Sun Jul 23 16:01:47.294 [initandlisten] db version v2.4.9
licode_1  | Sun Jul 23 16:01:47.294 [initandlisten] git version: nogitversion
licode_1  | Sun Jul 23 16:01:47.294 [initandlisten] build info: Linux orlo 3.2.0-58-generic #88-Ubuntu SMP Tue Dec 3 17:37:58 UTC 2013 x86_64 BOOST_LIB_VERSION=1_54
licode_1  | Sun Jul 23 16:01:47.294 [initandlisten] allocator: tcmalloc
licode_1  | Sun Jul 23 16:01:47.294 [initandlisten] options: { dbpath: "/opt/licode/build/db", fork: true, logpath: "/opt/licode/build/mongo.log", nojournal: true }
licode_1  | **************
licode_1  | Unclean shutdown detected.
licode_1  | Please visit http://dochub.mongodb.org/core/repair for recovery instructions.
licode_1  | *************
licode_1  | Sun Jul 23 16:01:47.295 [initandlisten] exception in initAndListen: 12596 old lock file, terminating
licode_1  | Sun Jul 23 16:01:47.295 dbexit:
licode_1  | Sun Jul 23 16:01:47.295 [initandlisten] shutdown: going to close listening sockets...
licode_1  | Sun Jul 23 16:01:47.295 [initandlisten] shutdown: going to flush diaglog...
licode_1  | Sun Jul 23 16:01:47.295 [initandlisten] shutdown: going to close sockets...
licode_1  | Sun Jul 23 16:01:47.295 [initandlisten] shutdown: waiting for fs preallocator...
licode_1  | Sun Jul 23 16:01:47.295 [initandlisten] shutdown: closing all files...
licode_1  | Sun Jul 23 16:01:47.295 [initandlisten] closeAllFiles() finished
licode_1  | Sun Jul 23 16:01:47.295 dbexit: really exiting now
licode_1  | [licode] SuperService ID Sun Jul 23 16:01:52.462 Error: couldn't connect to server localhost:27017 at src/mongo/shell/mongo.js:147
licode_1  | [licode] SuperService KEY Sun Jul 23 16:01:52.513 Error: couldn't connect to server localhost:27017 at src/mongo/shell/mongo.js:147
licode_1  | sed: -e expression #1, char 25: unterminated `s' command
licode_1  | sed: -e expression #1, char 26: unterminated `s' command
licode_1  | Starting Rabbitmq
licode_1  | Warning: PID file not written; -detached was passed.
licode_1  | Starting Nuve
licode_1  | /opt/licode/nuve/nuveAPI/logger.js:4
licode_1  | var logFile = config.logger.configFile ||  '../log4js_configuration.json';
licode_1  |                            ^
licode_1  |
licode_1  | TypeError: Cannot read property 'configFile' of undefined
licode_1  |     at Object.<anonymous> (/opt/licode/nuve/nuveAPI/logger.js:4:28)
licode_1  |     at Module._compile (module.js:570:32)
licode_1  |     at Object.Module._extensions..js (module.js:579:10)
licode_1  |     at Module.load (module.js:487:32)
licode_1  |     at tryModuleLoad (module.js:446:12)
licode_1  |     at Function.Module._load (module.js:438:3)
licode_1  |     at Module.require (module.js:497:17)
licode_1  |     at require (internal/module.js:20:19)
licode_1  |     at Object.<anonymous> (/opt/licode/nuve/nuveAPI/mdb/tokenRegistry.js:5:36)
licode_1  |     at Module._compile (module.js:570:32)
licode_1  | Starting erizoController
licode_1  | Starting erizoAgent
licode_1  | Starting basicExample
licode_1  | /opt/licode/licode_config.js:1
licode_1  | (function (exports, require, module, __filename, __dirname) { config.erizoController.publicIP = '192.168.31.79';
licode_1  |                                                               ^
licode_1  |
licode_1  | ReferenceError: config is not defined
licode_1  |     at Object.<anonymous> (/opt/licode/licode_config.js:1:63)
licode_1  |     at Module._compile (module.js:570:32)
licode_1  |     at Object.Module._extensions..js (module.js:579:10)
licode_1  |     at Module.load (module.js:487:32)
licode_1  |     at tryModuleLoad (module.js:446:12)
licode_1  |     at Function.Module._load (module.js:438:3)
licode_1  |     at Module.require (module.js:497:17)
licode_1  |     at require (internal/module.js:20:19)
licode_1  |     at Object.<anonymous> (/opt/licode/erizo_controller/erizoController/erizoController.js:6:14)
licode_1  |     at Module._compile (module.js:570:32)
licode_1  | /opt/licode/licode_config.js:1
licode_1  | (function (exports, require, module, __filename, __dirname) { config.erizoController.publicIP = '192.168.31.79';
licode_1  |                                                               ^
licode_1  |
licode_1  | ReferenceError: config is not defined
licode_1  |     at Object.<anonymous> (/opt/licode/licode_config.js:1:63)
licode_1  |     at Module._compile (module.js:570:32)
licode_1  |     at Object.Module._extensions..js (module.js:579:10)
licode_1  |     at Module.load (module.js:487:32)
licode_1  |     at tryModuleLoad (module.js:446:12)
licode_1  |     at Function.Module._load (module.js:438:3)
licode_1  |     at Module.require (module.js:497:17)
licode_1  |     at require (internal/module.js:20:19)
licode_1  |     at Object.<anonymous> (/opt/licode/erizo_controller/erizoAgent/erizoAgent.js:7:14)
licode_1  |     at Module._compile (module.js:570:32)
licode_1  | cp: cannot stat '/opt/licode/erizo_controller/erizoClient/dist/erizo.js': No such file or directory
licode_1  | /opt/licode/licode_config.js:1
licode_1  | (function (exports, require, module, __filename, __dirname) { config.erizoController.publicIP = '192.168.31.79';
licode_1  |                                                               ^
licode_1  |
licode_1  | ReferenceError: config is not defined
licode_1  |     at Object.<anonymous> (/opt/licode/licode_config.js:1:63)
licode_1  |     at Module._compile (module.js:570:32)
licode_1  |     at Object.Module._extensions..js (module.js:579:10)
licode_1  |     at Module.load (module.js:487:32)
licode_1  |     at tryModuleLoad (module.js:446:12)
licode_1  |     at Function.Module._load (module.js:438:3)
licode_1  |     at Module.require (module.js:497:17)
licode_1  |     at require (internal/module.js:20:19)
licode_1  |     at Object.<anonymous> (/opt/licode/extras/basic_example/basicServer.js:10:14)
licode_1  |     at Module._compile (module.js:570:32)
licode_licode_1 exited with code 0
```
```
Docker stop licode
Docker start licode
```
An error occurred after running the above command

**Comment by wuxingzhong** [comment]
## My English is not very good,  凑合着看吧!! ^_^

**Comment by jcague** [comment]
how did you run the docker?

**Comment by wuxingzhong** [comment]
use docker-compose  or  docker run  , the same error ...

**Comment by jcague** [comment]
can you follow the steps in http://licode.readthedocs.io/en/master/docker/ and try again please?

**Comment by wuxingzhong** [comment]
[root@bogon licode]# MIN_PORT=30000; MAX_PORT=31000; sudo docker run --name licode -p  3000:3000 -p $MIN_PORT-$MAX_PORT:$MIN_PORT-$MAX_PORT/udp -p 3001:3001  -p 8080:8080 -e "MIN_PORT=$MIN_PORT" -e "MAX_PORT=$MAX_PORT" -e "PUBLIC_IP=127.0.0.1" docker.io/lynckia/licode:latest
No parameters -- starting everything
Running NVM
Found '/opt/licode/.nvmrc' with version <6.9.2>
Now using node v6.9.2 (npm v3.10.9)
[licode] Starting mongodb
about to fork child process, waiting until server is ready for connections.
forked process: 256
all output going to: /opt/licode/build/mongo.log
child process started successfully, parent exiting
[licode] Creating superservice in localhost/nuvedb
MongoDB shell version: 2.4.9
connecting to: localhost/nuvedb
Mongo Logs:
Wed Jul 26 12:17:47.905 [initandlisten] MongoDB starting : pid=256 port=27017 dbpath=/opt/licode/build/db 64-bit host=ca963b7c8f22
Wed Jul 26 12:17:47.905 [initandlisten] db version v2.4.9
Wed Jul 26 12:17:47.905 [initandlisten] git version: nogitversion
Wed Jul 26 12:17:47.905 [initandlisten] build info: Linux orlo 3.2.0-58-generic #88-Ubuntu SMP Tue Dec 3 17:37:58 UTC 2013 x86_64 BOOST_LIB_VERSION=1_54
Wed Jul 26 12:17:47.905 [initandlisten] allocator: tcmalloc
Wed Jul 26 12:17:47.905 [initandlisten] options: { dbpath: "/opt/licode/build/db", fork: true, logpath: "/opt/licode/build/mongo.log", nojournal: true }
Wed Jul 26 12:17:47.906 [initandlisten]
Wed Jul 26 12:17:47.906 [initandlisten] ** WARNING: Readahead for /opt/licode/build/db is set to 4096KB
Wed Jul 26 12:17:47.906 [initandlisten] **          We suggest setting it to 256KB (512 sectors) or less
Wed Jul 26 12:17:47.906 [initandlisten] **          http://dochub.mongodb.org/core/readahead
Wed Jul 26 12:17:48.030 [FileAllocator] allocating new datafile /opt/licode/build/db/local.ns, filling with zeroes...
Wed Jul 26 12:17:48.030 [FileAllocator] creating directory /opt/licode/build/db/_tmp
Wed Jul 26 12:17:48.095 [FileAllocator] done allocating datafile /opt/licode/build/db/local.ns, size: 16MB,  took 0.032 secs
Wed Jul 26 12:17:48.095 [FileAllocator] allocating new datafile /opt/licode/build/db/local.0, filling with zeroes...
Wed Jul 26 12:17:48.120 [FileAllocator] done allocating datafile /opt/licode/build/db/local.0, size: 64MB,  took 0.024 secs
Wed Jul 26 12:17:48.127 [websvr] admin web console waiting for connections on port 28017
Wed Jul 26 12:17:48.127 [initandlisten] waiting for connections on port 27017
Wed Jul 26 12:17:53.131 [initandlisten] connection accepted from 127.0.0.1:56280 #1 (1 connection now open)
Wed Jul 26 12:17:53.134 [FileAllocator] allocating new datafile /opt/licode/build/db/nuvedb.ns, filling with zeroes...
Wed Jul 26 12:17:53.176 [FileAllocator] done allocating datafile /opt/licode/build/db/nuvedb.ns, size: 16MB,  took 0.042 secs
Wed Jul 26 12:17:53.178 [FileAllocator] allocating new datafile /opt/licode/build/db/nuvedb.0, filling with zeroes...
Wed Jul 26 12:17:53.197 [initandlisten] connection accepted from 127.0.0.1:56281 #2 (2 connections now open)
Wed Jul 26 12:17:53.201 [FileAllocator] done allocating datafile /opt/licode/build/db/nuvedb.0, size: 64MB,  took 0.018 secs
Wed Jul 26 12:17:53.202 [FileAllocator] allocating new datafile /opt/licode/build/db/nuvedb.1, filling with zeroes...
Wed Jul 26 12:17:53.207 [conn1] build index nuvedb.services { _id: 1 }
Wed Jul 26 12:17:53.227 [FileAllocator] done allocating datafile /opt/licode/build/db/nuvedb.1, size: 128MB,  took 0.021 secs
Wed Jul 26 12:17:53.229 [conn1] build index done.  scanned 0 total records. 0.021 secs
Wed Jul 26 12:17:53.229 [conn1] end connection 127.0.0.1:56280 (1 connection now open)
Wed Jul 26 12:17:53.233 [conn2] end connection 127.0.0.1:56281 (0 connections now open)
Wed Jul 26 12:17:53.295 [initandlisten] connection accepted from 127.0.0.1:56282 #3 (1 connection now open)
Wed Jul 26 12:17:53.299 [conn3] end connection 127.0.0.1:56282 (0 connections now open)
[licode] SuperService ID 59788871c68718d80e3f1fd5
[licode] SuperService KEY 22889
Starting Rabbitmq
Warning: PID file not written; -detached was passed.
Starting Nuve
2017-07-26 12:17:59.076  - ERROR: RPC - message: AMQP connection error killing process, errorMsg: code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 5672
Starting erizoController
Starting erizoAgent
Starting basicExample
2017-07-26 12:18:03.028  - INFO: ErizoAgent - message: launched new ErizoJS, erizoId: f250b76f-d8bc-e0ca-a0be-29d2e1e0b73b
(node:420) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
(node:419) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
[erizo-f250b76f-d8bc-e0ca-a0be-29d2e1e0b73b] (node:432) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
[erizo-f250b76f-d8bc-e0ca-a0be-29d2e1e0b73b] 2017-07-26 12:18:03.454  - INFO: ErizoJS - message: Started, erizoId: f250b76f-d8bc-e0ca-a0be-29d2e1e0b73b
cp: cannot stat '/opt/licode/erizo_controller/erizoClient/dist/erizo.js': No such file or directory
Cleaning basic example rooms
2017-07-26 12:18:08.221  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respondr, attemptsLeft: 5
2017-07-26 12:18:16.230  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respondr, attemptsLeft: 4
2017-07-26 12:18:24.234  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respondr, attemptsLeft: 3
2017-07-26 12:18:32.240  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respondr, attemptsLeft: 2
2017-07-26 12:18:40.248  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respondr, attemptsLeft: 1
2017-07-26 12:18:43.249  - ERROR: ErizoController - message: addECtoCloudHandler cloudHandler does not respond - fatal

**Comment by wuxingzhong** [comment]
thank you very much !!!

**Comment by speigg** [comment]
I see the same problem, happens quite frequently. Removing the container (`docker-compose rm` and running again fixes it temporarily.

**Comment by wuxingzhong** [comment]
It means every time you want to run licode，  you should to remove the container first。

**Comment by jcague** [comment]
current docker image is not ready to be used by stopping/starting container, you should remove them always, that's probably the cause.

**Comment by wuxingzhong** [comment]
thank you!

**Comment by steven8274** [comment]
I don't use original Dockerfile directly, I run a ubuntu 14.04 container and download licode in it, than install licode in it, finally I saved the container as a image(At the same time, I modified the Dockerfile to make docker container first process just do the job 'ping 127.0.0.1').At last, you can use the image to run a container for any times.You should enter the container and start licode manully.

**Comment by wuxingzhong** [comment]
Thank you.  That's a good idea.
