### ISSUE TITLE
No video on firefox

### ISSUE THREAD

**Issue by yeyingxian** [lynckia/licode#982]
I have installed the newest licode from github, and started basic example. But it seems basic example is broken for Firefox, no prompts pop up for asking permission to use camera. I have debug the code and found that the problem is produced by using adapter.js. The code calling getUserMedia() in erizo_controller/erizoClient/src/Connection.js before using adapter.js was

            if (config.video && Erizo.getBrowser() === 'mozilla') {
                var ffConfig = {video:{}, audio: config.audio, screen: config.screen};
                ...
                if (config.video.optional !== undefined) {
                    ffConfig.video.frameRate =  config.video.optional[1].maxFrameRate;
                }
                if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
                    promise = navigator.mediaDevices.getUserMedia(ffConfig).then(callback);
                    // Google compressor complains about a func called catch
                    promise['catch'](error);
                    return;
                }
            }
            
ffConfig.video.frameRate was set to a single value like 20. But now, the code in Connection.js call navigator.mediaDevices.getUserMedia directly without modifying ffConfig.video.frameRate, leaving it being an object like {min:10, max:20}, which brings problem in firefox

**Comment by arsenicraghav** [comment]
Do you get any errors in the console ? anything at all ?

**Comment by jcague** [comment]
@yeyingxian I see the same issue but it's because of some incompatibility between Firefox and my webcam, which doesn't seem to work. I tried with a different webcam and now it works right. You can change the max framerate to a different value (like 30) or choose another webcam to see if it works.

**Comment by yeyingxian** [comment]
@jcague Thanks for your replay. I changed the max framerate to 30 and it works now!
