### ISSUE TITLE
Issue with the source code of unminified version of Erizo.js and Nuve.js

### ISSUE THREAD

**Issue by arsenicraghav** [lynckia/licode#984]
Does anyone know, what is best practice to use the one combined source file for Erizo.js and Nuve.js instead of minified one which is generated ? I guess we should have both options as developers.

**Comment by nineKnight** [comment]
Hi @arsenicraghav ,
    Actually, I handle it in notepad++, using a plugin named JSTool ( download in Plugin Manager is needed ), to format the scripts.
    BTW, I can't agree more with your opinion.

**Comment by jcague** [comment]
@lodoyun just added source maps also for the debug version of ErizoClient in #987 , it should help you to develop and debug things. Please reopen this ticket again if it doesn't work for you.
