### ISSUE TITLE
Audio-only stream subscription does not work (worked earlier)

### ISSUE THREAD

**Issue by jjahifi** [lynckia/licode#985]
**Description**

Using audio only streams with Opus and higher bandwith does not work in master from Sunday 23rd July.

Works with V2. Not tested with V3.

**Steps to reproduce the issue:**

Publisher seems to get ready fine, but subscriptions do not work. 

I have prepared simple files to reproduce the error. This is expected to be run from an Ubuntu 14.04 machine with a camera and an audio system.  The used rtp_media_config.js added, licode_config.js in default settings. The files are in the attached zip-file.

The procedure is as follows (basic example is assumed to be installed):

1. Create directory ~/licode/extras/bugtest
2. Copy the file showbug.js to that directory. Copy the right version of nuve.js to that directory.
3. Create directory ~/licode/extras/bugtest/public
4. Copy files record.html, record.js, play.html, and play.js to that directory. Copy relevant version of erizo.js to that directory (tested with the debug version of the cloned master)
5. Copy initBugTest.sh to ~/licode/scripts
6. Start terminal
7. cd licode
8. ./script/initLicode.sh
9. Start terminal
10. cd licode
11. ./script/initBugTest.sh
12. Open Chrome
13. Open page localhost:9001/record.html
14. Licode log shows that the publisher gets ready in a fine way (log shown in figure1.png)
15. Open Chrome on the same machine or another machine (I have tried both)
16. Open page your_licode_server_ip:9001/play.html
17. The licode log says SUBSCRIBER READY, but there are constant errors in the Licode log. No sound. Logged errors shown in figure2.png.

**Describe the results you received:**

Licode log shows that the publisher should be ok. It also says that the subscriber is ready, but no sound. In addition, constant stream of errors. Shown in figure2.png

**Describe the results you expected:**

Expected behaviour the same as with V2. Publisher ready, bandwith renegotiated. Subscribers ready, sound played, no errors.

**Additional information you deem important (e.g. issue happens only occasionally):**

I have not tested this with V3.

**Licode commit/release where the issue is happening**

Clone from Sunday 23rd July.

**Additional environment details (Local, AWS, Docker, etc.):**

Installation from source on clean Ubuntu 14.04 LTS. 

[bugtest.zip](https://github.com/lynckia/licode/files/1179475/bugtest.zip)

**Comment by jcague** [comment]
I was able to reproduce this issue. Working on fix it. Thanks for the info @jjahifi!
