### ISSUE TITLE
ICE connection failed on publishing . Please advice .

### ISSUE THREAD

**Issue by yogeshgo05** [lynckia/licode#994]
https://test.vidconf.co.uk:3001/ , This is running on ec2 . With public IP setup for erizoController and Agent . 

I don't see a reason why this should be happening  on basic example . It happens after 20 seconds or so after it loads .

<img width="1272" alt="screen shot 2017-08-02 at 12 07 33 pm" src="https://user-images.githubusercontent.com/601209/28890524-3ae139aa-777c-11e7-8a6d-55e63c8ff0dd.png">

<img width="1079" alt="screen shot 2017-08-02 at 4 40 35 pm" src="https://user-images.githubusercontent.com/601209/28899655-3063c928-77a1-11e7-8d79-b6fd396df6d9.png">

**Comment by lodoyun** [comment]
That sounds like you didn't  open UDP ports in your aws instance. You must open a range of ports in your instance and then either put that range in `licode_config.js` under `config.erizo.minport` and `config.erizo.maxport` or leave those two at `0` and limit the ephemeral port range (more info [here](http://www.ncftp.com/ncftpd/doc/misc/ephemeral_ports.html) )

Each connection (publish or subscribe) will need one of those ports so keep that in mind.

**Comment by yogeshgo05** [comment]
What if ec2 instance behind a load balancer . It seems that problem is gone now . I have got minport and maxport to be zero .

**Comment by lodoyun** [comment]
The IP and the available ports are discovered using [ICE](https://tools.ietf.org/html/rfc5245). 
Setting minport and maxport to 0 means that Licode will randomly select ports from all the available range, but if you don't open all of them in the security group of your aws instance connections could fail from time to time.

I'm not entirely sure I understand how the load balancer fits in with Licode in your architecture. If you want to distribute load between several licode servers, that's not the way to do it. If you want to use it to load balance among several servers of your app, I would separate it from Licode and run licode in a different instance.

**Comment by sebastianfelipe** [comment]
No man, I tried what you say, because I had the same problem, and nothing. ERROR:  ICE Connection Failed on undefined instead :/

**Comment by sebastianfelipe** [comment]
When the connection begins to establish, it says there's no candidates

**Comment by sebastianfelipe** [comment]
Found the solution. Configure the config.erizoAgent.publicIP and config.erizoController.publicIP  <with your public ip> (also the min and max UDP ports). Hope it works 👍
