### ISSUE TITLE
Setting expiration time for the tokens 

### ISSUE THREAD

**Issue by arsenicraghav** [lynckia/licode#995]
Does Licode has any existing mechanism to set expiration for tokens or we need to implement our own, using the Hmac ?

**Comment by lodoyun** [comment]
Tokens expire after being consumed or after 3 hours (see [here](https://github.com/lynckia/licode/blob/master/nuve/nuveAPI/mdb/tokenRegistry.js#L83)).

**Comment by arsenicraghav** [comment]
@lodoyun I can see that we have a field in the token object that captures the time of creation but  actually I was thinking about these tokens more in terms of Access and Refresh Token. 

say :
```
exports.verify = function(data, hash) {
    /* returns INVALID,  VALID,  EXPIRING  status of token */
 }
```

**Comment by lodoyun** [comment]
Nuve tokens are one-use only, they don't provide access to the room for a period of time, they are *consumed* once the user gets in the room. If the user leaves the room, a new token is needed to get in again. Refreshing a token does not make sense in this context.
At the same time, if a token is not consumed in a 3 hour period, it is invalidated. The generation time is stored for that purpose only.The recommended action here is generating a new one. 

If what you're looking for is a way to remove a user from a room after a period of time, there are other ways to do it. For instance you can use [deleteUser](https://github.com/lynckia/licode/blob/master/nuve/nuveClient/src/N.API.js#L86)

Could you explain what's the behaviour you want to get for the application? It would be easier for me if I could understand what you want to build and we can go back to details in the tokens if that's the way to do it.

**Comment by arsenicraghav** [comment]
The scenario is that a user is granted a token which is having an expiration time, and once such a token is issued then user can then present it to the  server and gets access to the room so does not involve generating a new token each time, such type of token can also be extended to restrict access to other resources in Licode, this is like any of the CPaaS where access token and refresh tokens are used.

something like this:  https://tokbox.com/developer/guides/create-token/

**Comment by lodoyun** [comment]
In the guide you're linking they recommend not reusing tokens and generating them every time a client needs one. We're not only recommending it but enforcing it. I don't see the use case where refreshing the token is better than creating a new one in the context of Licode.

Regarding roles, you can configure and use [roles in Licode](http://lynckia.com/licode/roles.html).
