### ISSUE TITLE
Seeking Explanation on statements present in REDME.md  of Erizo. 

### ISSUE THREAD

**Issue by arsenicraghav** [lynckia/licode#998]
> As of now, the only application built using the library is a streaming application that connects via TCP to a server application built on top of node.js.
> 
> The node.js app is not released but the code should provide an example on how the SDP exchange is made.
> The examples are unusable as of now, but they can help to understand the API.
> In the future, we will include here tests and updated examples.
> 

a)   **the only application built using the library is a streaming application** : Does that mean other kinds of application can not be built as of now ?

b) **The node.js app is not released**  : which node.js app are we referring to 

c) **The examples are unusable as of now** :  which examples ? (I hope it's licode demos)

Does Erizo mix different streams currently or not ? It's simply forwarding the streams ?

Please advise as soon as possible .Thank

**Comment by aalonsog** [comment]
Hi @arsenicraghav, that README is outdated. We are going to remove it ASAP. Please, refer to [Licode documentation](http://lynckia.com/licode) or ask in [Licode forum](http://discourse.lynckia.com/) to get updated information. Sorry for the inconvenience.
